### ISSUE TITLE
Roundcube silently fails to add CardDAV instances with invalid URLs

### ISSUE THREAD

**Issue by cPKoree** [mstilkerich/rcmcarddav#279]
**Description**
When attempting to add a CardDAV instance with a malformed URL (i.e., ' https://server' with a space instead of 'https://server'), no feedback is provided in the Roundcube UI regarding this failure.
Instead, the user is presented with a blank interface:

This behavior is a problem, as a user would expect an invalid URL entry to be rejected with a corresponding pop-up error.

**Reproduction Steps**
In Roundcube, click 'Settings'.
Click 'CardDAV'.
For the Addressbook name, user, and password, provide any input (i.e., 'aaaa').
For the URL, use the following (make sure to include the leading space): ' https://server.com'.
Click 'Save'.
Note that this panel immediately turns white, with no further notification as to what has occurred.

**Expected Resolution**
One would expect for this scenario to result in an 'invalid/malformed URL' type error pop-up, similar to if you tried to save with empty fields.

**Comment by METEO64** [comment]
Hi PKoree,
Did you check the errors logs?
There is maybe a PHP Fatal error...

**Comment by mstilkerich** [comment]
With the current v4 development branch, this issue is fixed to the extent that no fatal PHP error is risen anymore, however, the user will only be displayed "no addressbooks found". The logs will contain a more detailed error message. I'm not sure yet on how much effort I want to spend to provide specific error messages for errors in the input data.

**Comment by mstilkerich** [comment]
Note to self: Consider `filter_var(FILTER_VALIDATE_URL)`

https://www.php.net/manual/en/function.filter-var.php
https://www.php.net/manual/en/filter.filters.validate.php

**Comment by mstilkerich** [comment]
Fixed on 4.1
