### ISSUE TITLE
Settings/Contacts/Sorting column in Roundcube does not work with CardDAV Addressbook

### ISSUE THREAD

**Issue by JMA-Github** [mstilkerich/rcmcarddav#325]
When I change the sorting column i.E. to Last Name, it will have the expected effect in my Personal Addressbook.
All contacts are sorted ba "Last Name".
But, contacts in my CardDAV Addressbook (connected to a Nextcloud based CardDAV-Server) will always be sorted by "Display-Name". The change of "Sorting Column" in the settings has no effect.

**Comment by blind-coder** [comment]
Please check if you actually HAVE a lastname / firstname set in your contacts. NextCloud does not automatically extract those from the Display Name, contrary to how pretty much every other service does it.

**Comment by JMA-Github** [comment]
Lastname and Firstname are set . I've checked it in the contact edit window of RC and in the database-table carddav_contacts.
I figured out, that 3 columns are filled (name, firstname, surname) 
name seems to be build from firstname + surname
When I enter a "display name " in RC, column "name" is filled with the "display name"
The column "showas" is always empty
The order in the contact list is always by coulumn "name"

**Comment by mstilkerich** [comment]
Thanks for reporting this, this broke with 968fe9f472e25561dab928d6e2bd425e7fc97762.

I think this should be fixed in roundcube and created a pull request roundcube/roundcubemail#7758, but I'll also fix it in rcmcarddav to restore the functionality.

**Comment by mstilkerich** [comment]
Fixed in v4.1. If you feel adventurous you can try that branch.
