### ISSUE TITLE
rcmcarddav does not work with new composer 2.x

### ISSUE THREAD

**Issue by JMA-Github** [mstilkerich/rcmcarddav#326]
after updating composer to version 2.0.7. I tried to update carddav.
I got the following error message from composer:
"Failed to extract roundcube/carddav: (9) unzip -qq  '/www/htdocs/v131228/round2/vendor/composer/tmp-a25b62ba601ae473052449dfc597dd28' -d '/www/htdocs/v131228/round2/vendor/composer/634c3f63'
unzip:  cannot find or open /www/htdocs/v131228/round2/vendor/composer/tmp-a25b62ba601ae473052449dfc597dd28.
    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix"

With composer Version 1.x the update of carddav is working still fine.

Regards

**Comment by mstilkerich** [comment]
Hello,

  you need roundcube/plugin-installer version 0.2.0, see [here](https://roundcube.net/news/2020/11/04/installer-update-for-composer-v2). RCMCardDAV does not depend on an older plugin-installer version, so it's simply a matter of running `composer update` in your roundcube directory - given that `composer.json` of roundcube or any used package does not have a dependency that prevents usage of plugin-installer 0.2.0.

So run `composer update` and check the output to make sure plugin-installer 0.2.0 was installed.

**Comment by mstilkerich** [comment]
See also #311
