### ISSUE TITLE
"Add to addressbook" function within mails not working properly

### ISSUE THREAD

**Issue by brrrrrrrt** [mstilkerich/rcmcarddav#332]
when reading a mail users have the option to click on a senders name and select "Add to addressbook".

it looks like it is working, users get two messages on the bottom right corner:

 - CardDAV addressbook 'XY' synchronized (Took 1 seconds)
 - Contact successfully added to address book.

no errors are logged, the contact is added, BUT **without email address**, see attached images.

it does work without problems, using the local addressbook which is not synced to the cloud.

![Bildschirmfoto von 2021-02-01 17-13-33](https://user-images.githubusercontent.com/4489013/106489505-2060b900-64b5-11eb-8e1f-a09cf2e4e04d.png)
![Bildschirmfoto von 2021-02-01 17-14-02](https://user-images.githubusercontent.com/4489013/106489504-1fc82280-64b5-11eb-913f-024da70f1127.png)

**Comment by mstilkerich** [comment]
Good catch! The cosmetic thing about the somewhat unexpected resync message popup is already fixed on master. About the missing email address... fix coming in a minute :-)
