### ISSUE TITLE
Skip certain address books

### ISSUE THREAD

**Issue by benbeek** [mstilkerich/rcmcarddav#335]
I use a Synology server to maintain address books. This works very good with your Roundcube plugin! A $prefs setting in config.inc.php for my Synology server with url "http://{ipaddress}:5000/carddav/{username}/" picks up all the address books of that useraccount at once.

But I would like to skip the default address books that Synology defines for every user: 
'My Contacts', 'Team Contacts', 'Suggested'.

So an extra setting in config.inc.php with that functionality like:
 'skip_books' => array('My Contacts', 'Team Contacts', 'Suggested')
would be very welcome.

And: thanks for this great plugin!

**Comment by mstilkerich** [comment]
Hello,

  thanks, I'm happy you like the plugin!

The intended way to disable "unwanted" addressbooks is to deactivate them in the settings pane. I think it should be a choice of the user, not the admin, which of their addressbooks a user wants to use within roundcube. I don't see why an admin would want to limit the addressbooks presented to the user.

**Comment by benbeek** [comment]
Hi Michael,

I could understand your view if there was no setting in config.inc.php that fully hides CardDav from the setting menu, depriving users all rights to do anything with the addressbooks. So, if that is ok, my proposal should be ok for sure ;-)
But I already found another way to do it in the Synology server in somewhat hidden setting for the contactbooks, that hides specific address books for the user inside the contacts app on the Synology server. I found out that they then are also excluded from the CardDav connection. This is not documented as such, but it works.

I also noticed that, if a new contactbook is added on the Synologyserver, that new book is not automatic discovered by your CardDav plugin. I can of course delete everything and have your plugin discover all the addressbooks again (including the new one), but maybe there is a more elegant way to do that?

Regards,
Ben

**Comment by mstilkerich** [comment]
Yes, the setting to hide the preferences entirely from a user is also one that makes no sense from my point of view, but the plugin has grown over the years... But I'm trying to avoid adding more and more settings that need to be maintained afterwards.

Concerning re-discovery to add new/delete removed addressbooks, this is actually an open feature that I intend to address with the broader scope for #48. It's on the roadmap for 4.2.0, at the moment I am wrapping up 4.1.0 and my top priority at this point is on test cases. So currently, unfortunately there is no more elegant way to do this yet..

**Comment by benbeek** [comment]
Thanks for your fast and clear reply Michael.
And thanks again for your very useful plugin!

Regards,
Ben
