### ISSUE TITLE
Consider using utf8mb4 (utf8mb4_unicode_ci) in MySQL/MariaDB

### ISSUE THREAD

**Issue by KoljaL** [mstilkerich/rcmcarddav#344]
for RC1.5 support.
See here: https://github.com/roundcube/roundcubemail/issues/7113

**Comment by mstilkerich** [comment]
rcmcarddav has been using utf8mb4 with MySQL for a long time already.

Side note: rcmcarddav has its own tables, it is no problem for it to have different charset than roundcube.
