### ISSUE TITLE
RC 1.4.11 | RC Plugins kolab calendar 3.5.7 | bday calendar with carddav contacts

### ISSUE THREAD

**Issue by mdkeil** [mstilkerich/rcmcarddav#348]
Hello,

I tryed using kolab/calendar with Roundcube 1.4.11, especially the bday-calendar function, working fine with local contacts. But I get an error, if choose some carddav-addressbook (rcmcarddav plugin). The carddav adressbook is working as expected,

Error in RC-log:

`PHP Error: Addressbook source (carddav_3) not found! in /var/www/html/program/include/rcmail.php on line 262 (GET /?_task=calendar&source=__bdays__&_action=load_events&start=2021-06-21T00%3A00%3A00&end=2021-06-28T00%3A00%3A00&_=1624352198493)`

**Comment by mstilkerich** [comment]
Hello,

   the calendar plugin uses its own calendar "task". This task does not exist in plain roundcube and the carddav plugin does not register for it. Therefore the addressbooks are not available inside calendar.

It should suffice to add the calendar task to the list of tasks where the carddav plugin is loaded. I added a fix in the master branch, you can also easily adapt carddav.php yourself (see the referenced commit above for the needed change).
