### ISSUE TITLE
Error with CardDavClient

### ISSUE THREAD

**Issue by grosjo** [mstilkerich/rcmcarddav#350]
Hi
Using latest git (both roundcube and rcmcardav), I have the following error:

[18-Jul-2021 17:44:47 GMT] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to MStilkerich\CardDavClient\Account::__construct() must be of the type string, array given, called in /data/web/sites/grosjo.net/secure/mail/plugins/carddav/src/Config.php on line 161 and defined in /data/web/sites/grosjo.net/secure/mail/plugins/carddav/vendor/mstilkerich/carddavclient/src/Account.php:50
Stack trace:
#0 /data/web/sites/grosjo.net/secure/mail/plugins/carddav/src/Config.php(161): MStilkerich\CardDavClient\Account->__construct('https://grosjo....', Array, '', 'https://grosjo....')
#1 /data/web/sites/grosjo.net/secure/mail/plugins/carddav/src/Addressbook.php(1584): MStilkerich\CardDavAddressbook4Roundcube\Config::makeAccount('https://grosjo....', 'XXXX', 'XXXXX, 'https://grosjo....')
#2 /data/web/sites/grosjo.net/secure/mail/plugins/carddav/src/Addressbook.php(425): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->getCardDavObj()
#3 /data/web/sites/grosjo.net/secure/mail/program/actions/contacts/show.php(47): MStilkerich\CardDavAddressbook4Roundcu in /data/web/sites/grosjo.net/secure/mail/plugins/carddav/vendor/mstilkerich/carddavclient/src/Account.php on line 50

**Comment by mstilkerich** [comment]
The git version of rcmcarddav requires carddavclient version 1.2.0. You have to run `composer update --no-dev` to get your dependencies fixed. When you install the plugin using composer as recommended, this happens automatically.

**Comment by grosjo** [comment]
ok, but still, the problem remains for git version

**Comment by mstilkerich** [comment]
Can you please provide a bit more detail, specifically on what you tried to fix the issue? The error message clearly indicates that you have an old version of carddavclient installed which is not compatible with the git version of rcmcarddav. When installing the plugin as described in the docs I referenced you won't have the problem, including when installing the git master.

**Comment by mstilkerich** [comment]
Closing for lack of feedback
