### ISSUE TITLE
Not compatible with birthday calendar

### ISSUE THREAD

**Issue by JodliDev** [mstilkerich/rcmcarddav#351]
Hello
I noticed that this plugin does not seem to be compatible with the birthday calendar of the kolab_calendar plugin.
When debugging, I realised that calendars created with rcmcarddav are not returned when calling `rcmail::get_instance()->get_address_sources()`.

Can you give me some pointers as to why? If it is an easy fix, I am thinking of doing it myself and sending you a Pull Request :)

**Comment by mstilkerich** [comment]
Hello, it is already fixed in the current git master.

**Comment by mstilkerich** [comment]
See #348

**Comment by JodliDev** [comment]
Ah thank you very much! That is working :)

I am sorry for not finding that for myself. I searched the issues for "birthday" and came up empty but didnt think that "bday" could also lead to results :D
