### ISSUE TITLE
Unable to sync contacts with Baikal

### ISSUE THREAD

**Issue by mischapeters** [mstilkerich/rcmcarddav#352]
Hi,

I just installed carddav (v4.1.2) in Roundcube (1.4.11) and I keep getting the following error message:

```
<29v1bod1> DB Error: [1292] Incorrect datetime value: '1629730056' for column `roundcube`.`carddav_addressbooks`.`last_updated` at row 1 (SQL Query: UPDATE carddav_addressbooks SET `last_updated`='1629730056'  WHERE ((`id` = '6'))) in /roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (GET /?_task=addressbook&_action=list&_source=carddav_6&_page=1&_remote=1&_unlock=loading1629729756812&_=1629729754064)
```

I did try the route to uninstall the plugin, removing the tables and installing again but the error remains the same.
Anything I can do to make this work?

**Comment by mstilkerich** [comment]
Hello, which DB system and version are you using? You can try removing the `(string)` casts in carddav.php line 1409 and src/Addressbook.php line 1214 related to the last_updated field.

I wont be able to look into it myself before next weekend.

**Comment by mischapeters** [comment]
Thank you for your lightning fast response!
I knew I forgot something, MariaDB 10.5.12. :)
Will have a look to see if this helps and report back.

**Comment by mischapeters** [comment]
Removing (string) didn't do the trick.
Seeing the same error message as mentioned above.
I did see another error during login as well.
```
<f85umt0s> DB Error: [1060] Duplicate column name 'use_categories' (SQL Query: ALTER TABLE carddav_addressbooks ADD `use_categories` INT NOT NULL DEFAULT '0' AFTER `presetname`) in /roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login&_action=login)
```

When you have some time the coming weekend that would be great! We have survived without it so far. :)

**Comment by mstilkerich** [comment]
Hello,

  ok, so it appears your schema is not up to date (last_updated is not a datetime column in the current schema), because the migration scripts did not run successfully. Then the current code is run against an incompatible older database schema.

The error about the duplicate column shows that the first migration did not work. However, there should be no column use_categories at this schema revision.

Please try to drop all the carddav tables. Then log in to roundcube and observe the logs.
```sql
DROP TABLE IF EXISTS carddav_migrations, carddav_xsubtypes, carddav_group_user, carddav_groups, carddav_contacts, carddav_addressbooks;
```
Check that there is no carddav_table left in the output of this command:
```sql
show tables;
```
Then log into roundcube again and check for newly created log messages.

**Comment by mischapeters** [comment]
I did go through that process during one of my tries. Removing the tables and reinstall the plugin.
Is there a way I can (re-)run the migration script manually?

**Comment by mischapeters** [comment]
After removing the tables and logging back in, I got the following in the logs:
```
[25-Aug-2021 10:49:50 +0200]: <gb4r8elv> DB Error: [1146] Table 'roundcube.carddav_migrations' doesn't exist (SQL Query: SELECT `filename` FROM carddav_migrations) in /roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login&_action=login)

==> carddav.log <==
[25-Aug-2021 10:49:50 +0200]: <gb4r8elv> [5 ERR] Database::get (SELECT `filename` FROM carddav_migrations) ERROR: [1146] Table 'roundcube.carddav_migrations' doesn't exist 

```

**Comment by mstilkerich** [comment]
this message is normal on initial login when the tables do not exist yet. If there is nothing else, it looks good. Does it work?

**Comment by mischapeters** [comment]
YES IT DOES! Thank you very much for your help and patience. Issue closed. 👍 💯
