### ISSUE TITLE
Unable to update (non-category) groups containing duplicate members

### ISSUE THREAD

**Issue by eirikrye** [mstilkerich/rcmcarddav#356]
Hello,

- Roundcube 1.4.11
- RCMCardDAV 4.1.0
- SabreDAV 4.1.1

## Summary

If a group vCard (`X-ADDRESSBOOKSERVER-KIND:group`) contains duplicated members, the vCard will never be synced and any updates to the vCard (name, or members) will silently fail. No error is reported to the user. In fact, the user only sees a message that the group membership was successfully updated.

## Steps to reproduce:

1. Create a new group in Roundcube, in an addressbook using `use_categories=0`
2. See that the group object is created on the CardDAV server:
      
        BEGIN:VCARD
        VERSION:3.0
        PRODID:-//Sabre//Sabre VObject 4.3.5//EN
        UID:sabre-vobject-caeeb9d0-dd4a-46b7-9b1b-9f833d9302c4
        REV:2021-10-11T09:56:30Z
        N:rcmcarddav;;;;
        FN:rcmcarddav
        X-ADDRESSBOOKSERVER-KIND:group
        END:VCARD
3. Add a member in Roundcube, and see that the group vCard is updated:

        BEGIN:VCARD
        VERSION:3.0
        PRODID:-//Sabre//Sabre VObject 4.3.5//EN
        UID:sabre-vobject-caeeb9d0-dd4a-46b7-9b1b-9f833d9302c4
        REV:2021-10-11T09:56:30Z
        N:rcmcarddav;;;;
        FN:rcmcarddav
        X-ADDRESSBOOKSERVER-KIND:group
        X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:sabre-vobject-b80b2530-5ead-4a3a-a812-5
         a02fc95c57b
        END:VCARD

4. Now, using `curl`, update the group vCard on the CardDAV server to contain a duplicate of the same member:

        ~ % curl -u <redacted> https://<redacted>/addressbooks/<redacted>/addressbook/sabre-vobject-caeeb9d0-dd4a-46b7-9b1b-9f833d9302c4.vcf -XPUT --data-binary @- << EOF
        BEGIN:VCARD
        VERSION:3.0
        PRODID:-//Sabre//Sabre VObject 4.3.5//EN
        UID:sabre-vobject-caeeb9d0-dd4a-46b7-9b1b-9f833d9302c4
        REV:2021-10-11T09:56:30Z
        N:rcmcarddav;;;;
        FN:rcmcarddav
        X-ADDRESSBOOKSERVER-KIND:group
        X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:sabre-vobject-b80b2530-5ead-4a3a-a812-5
         a02fc95c57b
        X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:sabre-vobject-b80b2530-5ead-4a3a-a812-5
         a02fc95c57b
        END:VCARD
        EOF

From now on, any attempt to make changes to this group's name or its members will fail silently. SabreDAV actually returns a 412 error on its end - presumably because of an ETag mismatch - however RCMCardDAV will never synchronize the updated vCard and will never recover.

RCMCardDAV reports no problem with synchronization, and the `last_updated` timestamp for the address book is updated, but the specific group vCard with duplicated members is never synced.

Updating the vCard using external means to remove the duplicate entries will allow RCMCardDAV to recover on its next synchronization, again allowing updates to the group.

## Cause of duplicates

In an attempt to reproduce how users were able to end up with duplicated members, I noticed that replaying the `group-addmembers` action in the browser's debugger ended up creating a group with duplicate members. This group is subsequently affected by the same issue as above.

I assume there is some sequence of clicks, maybe in combination with a slow webserver or poor connection, causing these requests to be sent twice and practically "bricking" the whole contact group for future modification from within Roundcube itself.

**Comment by eirikrye** [comment]
Roundcube reports the following database error when attempting to process the duplicated member (when replaying the request):

```
errors: <8ec73735> [11-Oct-2021 13:22:42 +0000]: DB Error: [7] ERROR:  duplicate key value violates unique constraint "carddav_group_user_pkey"
DETAIL:  Key (group_id, contact_id)=(11384, 2788174) already exists. (SQL Query: INSERT INTO carddav_group_user("group_id","contact_id") VALUES ('11384','2553596'), ('11384','2788174'), ('11384','2788174')) in /var/www/html/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=addressbook&_framed=1&_action=group-addmembers)
carddav: <8ec73735> [11-Oct-2021 13:22:42 +0000]: [5 ERR] Database::insert (INSERT INTO carddav_group_user("group_id","contact_id") VALUES (?,?), (?,?), (?,?)) ERROR: [7] ERROR:  duplicate key value violates unique constraint "carddav_group_user_pkey"
DETAIL:  Key (group_id, contact_id)=(11384, 2788174) already exists.
carddav: <8ec73735> [11-Oct-2021 13:22:42 +0000]: [5 ERR] Failed to update group 11384: [7] ERROR:  duplicate key value violates unique constraint "carddav_group_user_pkey"
DETAIL:  Key (group_id, contact_id)=(11384, 2788174) already exists.
```

This is fair enough, however this error doesn't appear to be handled and a success status is returned to the user. Also, at this point RCMCardDAV has already updated the remote vCard with the duplicated entry.

Similar database errors do *not* appear to be printed when RCMCardDAV syncs

**Comment by mstilkerich** [comment]
This should now be fixed on master. It won't automatically fix the problem that a group card with duplicate members failed to sync in the past, and won't be updated during syncs again until a server-side change occurs.

To allow to fix this, I added a new action in the addressbook similar to the immediate resync option. This action allows to delete the local cache of an addressbook, meaning the next sync will fetch everything from scratch. Now rcmcarddav will be able to import the group cards containing duplicate members. If the card is stored back to the server (e.g. by changing name of the group, or any group memberships), the duplicate entry in the vcard will also be removed.
