### ISSUE TITLE
The plugin doesn't start within the Docker container

### ISSUE THREAD

**Issue by romu70** [mstilkerich/rcmcarddav#365]
First of all, I'm a bit lost at searching information about the Carddav plugin for Roundcube, so if this is not the right place, feel free to warn me.

Now the problem I'm facing. I run Rouncube through the official Docker image. And to install Carddav, I used this settings:

```
-e ROUNDCUBEMAIL_PLUGINS=carrdav
```

The Carddav settings don't appear in the RC settings, and in the logs, I get:

```
ERROR: Failed to load plugin file /var/www/html/plugins/carrdav/carrdav.php
```

This is clear, but not informative enough to diagnose the problem. Any help would be great to digg the problem. Thanks.

**Comment by mstilkerich** [comment]
Hello,

1) there is a typo in the plugin name
2) rcmcarddav is not part of the roundcube core, so it is not contained in the docker image. You need to build a custom image to include external plugins like this one, see the documentation of the docker image at https://hub.docker.com/r/roundcube/roundcubemail/

**Comment by mstilkerich** [comment]
There is an example at the end of the docker image‘s documentation that includes installation of an external plugin. You just have to replace `johndoh/contextmenu` in that example by `roundcube/carddav`

**Comment by romu70** [comment]
Perfect, thank a lot @mstilkerich.
