### ISSUE TITLE
A really stupid question... and I apologize

### ISSUE THREAD

**Issue by joaoherberto** [mstilkerich/rcmcarddav#367]
Is this plugin for only accessing an existing CardDAV server or does it also serve the Address book of a Roundcube account?

**Comment by mstilkerich** [comment]
Hello, this plugin is a CardDAV client, not a server. So yes, it allows you to use addressbooks on a CardDAV server in roundcube, but does not server roundcube‘s builtin addressbook via carddav.

**Comment by joaoherberto** [comment]
Thank you for clarifying.. much appreciated. I will close this now.
