### ISSUE TITLE
Disable the roundcube contacts pannel

### ISSUE THREAD

**Issue by azmeuk** [mstilkerich/rcmcarddav#372]
In order to force users to use the CardDAV service, it would be nice to entirely hide the "contact" pannel and settings from the roundcube interface.

I suggest implementing an option in rcmcarddav to do this.

What do you think?

**Comment by mstilkerich** [comment]
What do you mean by contacts panel? The addressbook management found under the contacts button is used for all sorts of addressbooks, including Carddav. The contacts area in the settings panel includes useful settings also for carddav addressbooks, including selection of the default addressbook.

**Comment by mstilkerich** [comment]
Hello,

  you can disable roundcube's builtin addressbooks by configuration:

```php
$config['address_book_type'] = '';
$config['autocomplete_addressbooks'] = [];
$config['collected_recipients'] = false;
$config['collected_senders'] = false;
```

In the address book management, you will then only see the active carddav addressbooks (assuming you have no other addressbook sources). You can configure carddav addressbooks to be read-only for admin presets as well if you don't want users to change the addressbooks, and you can also prevent users from manually creating carddav addressbooks.

Beyond that, I see little point in disabling the contacts section in roundcube entirely. In any case, I don't think rcmcarddav would be the right place for such functionality (I don't even know if a plugin can remove a standard task entirely from roundcube).

I also see no point in removing the contacts section from preferences, as it robs the user of the ability to configure personal preferences like how contacts are displayed. And again, this section belongs to roundcube, so I don't think rcmcarddav would be the right place to mess with it.

**Comment by azmeuk** [comment]
> Beyond that, I see little point in disabling the contacts section in roundcube entirely. 

As I provide my users a web interface to manage their CardDAV contacts, I prefer to not confuse them with several tools that do the same thing (i.e. contact management).

> In any case, I don't think rcmcarddav would be the right place for such functionality (I don't even know if a plugin can remove a standard task entirely from roundcube).

I can understand this. Maybe I can discuss this upstream.

**Comment by TCB13** [comment]
This works, however collected addresses are important. I've noticed that if I have those turn on they'll appear first on the address book list and the user will not see the DAV address book by default. Any tips around this?
