### ISSUE TITLE
Error 404 vcf not found

### ISSUE THREAD

**Issue by ParoTheParrot** [mstilkerich/rcmcarddav#381]
Got a strange error with 4.3.0 (baikal 0.6.1):

_Sync des CardDAV-Adressbuchs kk (-famAdr) fehlgeschlagen: GET html/card.php/addressbooks/knut/famadr/F9B50C33-AECC-4AFF-B6F2-AEA8E5B111FC.vcf HTTP request was not successful (404 Not Found): 4.0.2 Sabre\DAV\Exception\NotFound Card not found_

The addressbook is ok. Works fine with Thunderbird + cardbook.

Deleting the mentioned vcf brings up  a similar error with another vcf.

Any ideas? TIA

**Comment by ParoTheParrot** [comment]
I went trough several issues, but I didn't find a  solution or any advice.

**Comment by mstilkerich** [comment]
The URL without a leading slash looks suspicious, rcmcarddav will interpret it relative to the addressbook URL and therefore not find the card. I have never seen a Carddav Server return relative paths, I will check with the old Baikal you use.

**Comment by ParoTheParrot** [comment]
Wow - you brought me on the right track: the leading slash!
I look at my baikal system setting and found at "CardDAV base URI" : "html/card.php/". And - voilà - the missing slash!
I changed it to "/html/card.php/" and now it seems to work! 😀

**Comment by mstilkerich** [comment]
Doh should have checked my mail first... Just tried this with Baikal 0.6.1 and came to tell you it works fine for me with the default settings, though the paths reported by the server look like `/dav.php/addressbooks/citest/default/1cade77d-7b98-4a91-a5cc-3bc84c06a42b.vcf` :-)
