### ISSUE TITLE
no such table: carddav_accounts

### ISSUE THREAD

**Issue by hejnm1am** [mstilkerich/rcmcarddav#394]
1) build roundcube 1.6.0 with carddav plugin (use composer -- {"roundcube/carddav":"dev-master"})
2) configure sqlite3 database for roundcube, no carddav specific setting is used
3) start roundcube for the first time, sqlite3 database will be created
4) login to roundcube

 DB Error: [1] no such table: carddav_accounts (SQL Query: SELECT * FROM carddav_accounts WHERE (("user_id" = '1'))) in /var/www/program/lib/Roundcube/rcube_db.php on line 564 (POST /?_task=login&_action=login)

carddav: <d9831f1e> [5 ERR] Database::get (SELECT * FROM carddav_accounts WHERE (("user_id" = '1'))) ERROR: [1] no such table: carddav_accounts
[02-Sep-2022 09:20:01 Etc/UTC] PHP Fatal error:  Uncaught MStilkerich\CardDavAddressbook4Roundcube\Db\DatabaseException: [1] no such table: carddav_accounts in /var/www/plugins/carddav/src/Db/Database.php:494
Stack trace:
#0 /var/www/plugins/carddav/src/Db/Database.php(367): MStilkerich\CardDavAddressbook4Roundcube\Db\Database->internalGet(Array, Array, 'accounts', Array)
#1 /var/www/plugins/carddav/src/Frontend/AddressbookManager.php(133): MStilkerich\CardDavAddressbook4Roundcube\Db\Database->get(Array, Array, 'accounts')
#2 /var/www/plugins/carddav/src/Frontend/AddressbookManager.php(267): MStilkerich\CardDavAddressbook4Roundcube\Frontend\AddressbookManager->getAccountIds()
#3 /var/www/plugins/carddav/carddav.php(169): MStilkerich\CardDavAddressbook4Roundcube\Frontend\AddressbookManager->getAddressbookIds()
#4 /var/www/plugins/carddav/carddav.php(309): carddav->initPlugin()
#5 /var/www/program/lib/Roundcube/rcube_plugin_api.php(518): carddav->afterLogin(Array)
#6 /var/www/index.php(149): rcube_plugin_api->exec_hook('login_after', Array)
#7 /var/www/public_html/index.php(26): include('/var/www/index....')
#8 {main}
  thrown in /var/www/plugins/carddav/src/Db/Database.php on line 494

**Comment by mstilkerich** [comment]
Ouch, thanks for reporting this, might have sneaked into the 5.0 beta otherwise. It is fixed now on master!
