### ISSUE TITLE
Correct examples in ADMIN-SETTINGS.md

### ISSUE THREAD

**Issue by cm-schl** [mstilkerich/rcmcarddav#403]
Hi,
I'm not 100% sure, but I think the examples under https://github.com/mstilkerich/rcmcarddav/blob/master/doc/ADMIN-SETTINGS.md instead of `discovery_url` should contain just `url`.
I tried the example and it didn't work until i understood that `url` is the correct param...

**Comment by mstilkerich** [comment]
Hello,

  when you look up the documentation in the git repo, you will find the documentation that matches the software in the corresponding commit. The master branch reflects the current development line, which is RCMCardDAV v5. The admin settings in v5 have some changes to what they looked like in v4.

So for v4, please refer to the documentation of the corresponding release, which you find either directly in your plugin installation folder or by looking at the corresponding git tag.

For example, for v4.4.3 you can find it here:
https://github.com/mstilkerich/rcmcarddav/blob/v4.4.3/doc/ADMIN-SETTINGS.md
