### ISSUE TITLE
Incorrect assert in DelayedPhotoLoader in Roundcube 1.6.0+

### ISSUE THREAD

**Issue by ScottPeterJohnson** [mstilkerich/rcmcarddav#404]
DelayedPhotoLoader has the following assert in it, checking that the user variable is set in session:
```php
private function determineCacheKey(): string
    {
        [...]
        $userid = $_SESSION['user_id'];
        assert(is_string($userid), "user must be logged on to use photo cache");
```
However it seems in Roundcube 1.6.0+ the session user id will actually be an int, so this check should be `isset` instead of `is_string`.

**Comment by ScottPeterJohnson** [comment]
See here for roundcube change: https://github.com/roundcube/roundcubemail/blame/master/program/lib/Roundcube/rcube_user.php#L81

**Comment by mstilkerich** [comment]
Thanks for reporting this, I just found that after one of my last system upgrades, I forgot to adapt the php config file for the upgraded php version to enable assertions.

I'll commit a fix right away and will replace this by an Exception so it is not dependent on the assertion config anymore.
