### ISSUE TITLE
Nextcloud 2FA and use of app tokens

### ISSUE THREAD

**Issue by HF-B5** [mstilkerich/rcmcarddav#405]
Currently I use NextCloud 24.07 for my contacts (CARDDAV) and RoundCube 15 for accessing
my mails. If you enable 2FA in NC you must use an app token for authentication of
third party applications. I just tried it but no success. No big surprise. It would be nice 
to enable log in with an app token to NC.

**Comment by mstilkerich** [comment]
Hello,

  not sure what you mean by "app token". With 2FA, you can create "app passwords" in Nextcloud. If you create one for rcmcarddav and provide rcmcarddav with that app password, accessing your addressbooks should work just fine.

**Comment by HF-B5** [comment]
Hi,

>   not sure what you mean by "app token". With 2FA, you can create "app
> passwords" in Nextcloud. If you create one for rcmcarddav and provide
> rcmcarddav with that app password, accessing your addressbooks should
> work just fine.

of course app passwords and sorry, I tried it again
and now it works. Don't know why. Just close the issue.

Cheers
Helmut

Ich bin auch prima über ==== SIGNAL ==== zu erreichen!
[https://signal.org/download]

-- 
***@***.*** ***@***.***
PGP key fingerprint = 44DF 55B3 81C3 FAA6 6535  7995 FD99 4708 D33B BD63
--
Work less - Sail more
Brueder und Schwestern, auf zur Sonne, zur Freizeit!
                  ,~
                  |\
                 /| \
         ~^~ ^~ /_|__\~^~ ~^~
        ~^~^ ~ '======' ~^ ~^~
    jgs  ~^~ ~^ ~^~ ~^~ ~^ ~
--------------------
NO ADS, NO HTML-MAIL, NO ATTACHEMENTS IN PROPRIETARY FORMATS
