### ISSUE TITLE
predefined account problem

### ISSUE THREAD

**Issue by BlackZork** [mstilkerich/rcmcarddav#406]
roundcube 1.6.0
roundcubemail-plugin-carddav 4.4.4-1, archlinux (installed from [aur](https://aur.archlinux.org/packages/roundcubemail-plugin-carddav))
php 8.1.12
postgresql 14.5

I added prefefined personal addressbook from [this example](https://github.com/mstilkerich/rcmcarddav/blob/master/doc/ADMIN-SETTINGS.md#examples) with discovery url:

`'discovery_url' =>  'https://zork.pl/dav/addressbooks/user/%u/Default'`

carddav plugin complains in logs:

```
[root@black ~]# tail -f  /var/log/roundcubemail/carddav.log
[26-Nov-2022 21:45:44 +0000]: <iro4vmkn> [5 ERR] Database::get (SELECT "filename" FROM carddav_migrations) ERROR: [7] ERROR:  relation "carddav_migrations" does not exist
LINE 1: SELECT "filename" FROM carddav_migrations
                               ^ 

[26-Nov-2022 21:54:32 +0000]: <8vnc6ii1> [5 ERR] Error adding addressbook from preset Personal: The account's discovery URI must contain a hostname (got: ) 
```

No idea why carddav does not like my url.

**Comment by mstilkerich** [comment]
Hello,

  the first log message is normal on the very first login after installing the plugin.

Concerning your configuration, you probably used the documentation from the git master branch, not the one matching your release. In v4, the setting is called `url`, not `discovery_url`. There are also other changes, so I suggest you check the correct documentation for the v4 release.

See here https://github.com/mstilkerich/rcmcarddav/issues/403#issuecomment-1274491494
