### ISSUE TITLE
How to store by default “Trusted Senders” and “Collected Recipients” to a CardDAV addressbook?

### ISSUE THREAD

**Issue by dilyanpalauzov** [mstilkerich/rcmcarddav#409]
In RoundCube users can have addressbooks ‘Trusted senders” and “Collected senders”.  These addressbooks are by default stored in SQL.  These are controlled in roundcube/config/config.inc.php by:

```php
// The addressbook source to store automatically collected recipients in.
// Default: true (the built-in "Collected recipients" addressbook, source id = '1')
// Note: It can be set to any writeable addressbook, e.g. 'sql'
$config['collected_recipients'] = true;

// The addressbook source to store trusted senders in.
// Default: true (the built-in "Trusted senders" addressbook, source id = '2')
// Note: It can be set to any writeable addressbook, e.g. 'sql'
$config['collected_senders'] = true;
```

Please advice what settings shall I do in roundcube/config/config.inc.php or plugins/carddav/config.inc.php so that users by default (after the first login) store “Collected recipients” and “Trusted Senders” in writable CardDAV addressbook.  I want to avoid having addressbooks, which exist only in Roundcube, instead of uploading new contacts over CardDAV.  Moreover I do not want to ask users to make manual settings, as this is error-prone and cumbersome.

**Comment by mstilkerich** [comment]
The admin can set preset addressbooks for collected_senders/recipients by matching on the URL or name in a preset, as described in [ADMIN-SETTINGS.md](https://github.com/mstilkerich/rcmcarddav/blob/v4/doc/ADMIN-SETTINGS.md#using-presets-for-the-roundcube-trusted-senderscollected-recipients-addressbooks)

This is not meant to be overridden by the user. It is not possible to set an initial value that can later be overridden by the user. You cannot set it in the roundcube settings, because there you have to specify the ID of an addressbook, which in the case of carddav addressbooks is based on the database id of the addressbook and therefore not static.

**Comment by dilyanpalauzov** [comment]
I want to select as “collected senders" and "collected recipients” the addressbook `http://127.0.0.4/dav/addressbooks/user/%u/Default`.  So I set
```php
$prefs['_GLOBAL']['collected_recipients'] = [
    'preset'  => 'AEGEE Addressbook (CardDAV)',
    'matchurl' => '#http://127.0.0.4/dav/addressbooks/user/%u/Default#',
];
$prefs['_GLOBAL']['collected_senders'] = [
    'preset'  => 'AEGEE Addressbook (CardDAV)',
    'matchurl' => '#http://127.0.0.4/dav/addressbooks/user/%u/Default#',
];
```
There is one more parameter: `'matchname' => '/collected recipients/i'` . I do not understand towards what is this RegEx matched and why is this parameter necessary.  Do I have to use under `$prefs['_GLOBAL']['collected_senders'] ` `'matchname' => '/collected recipients/i',` (as the example suggests), or `'matchname' => '/collected senders/i'`?

Do I have to set in roundcube’s config.inc.php:
```php
$config['collected_recipients'] = false;
$config['collected_senders'] = false;
```
?

**Comment by dilyanpalauzov** [comment]
/tmp/carddav.log contains a lot of
```
[20-Dec-2022 15:38:50 +0000]: <5d4baf91> [5 ERR] Cannot set special addressbook collected_recipients, there are 0 candidates (need: 1) 
[20-Dec-2022 15:38:50 +0000]: <5d4baf91> [5 ERR] Cannot set special addressbook collected_senders, there are 0 candidates (need: 1) 
```
I do not understand how I can fix this error.

**Comment by dilyanpalauzov** [comment]
The loop in carddav.php:1440 is called with
LOOP START

match pattern /collected recipients/i match value AEGEE Addressbook (CardDAV) (AB of …@aegee.org) → no match → $isMatch is set to false
match pattern /^http:\/\/127.0.0.4\/dav\/addressbooks\/user\/aaa\/Default\/$/ match value http://127.0.0.4/dav/addressbooks/user/aaa/Default/ → $isMatch remains false, because it was initially set to true and if there is a mismatch, then it is set to false

LOOP END
Cannot set special addressbook collected_recipients, there are 0 candidates (need: 1)

How is this supposed to work?  The matchname is supposed to be matched with the DAV:displayname property and matchurl is matched with the URL and both need to match?  So matchname can be skipped, if I do not want to compare with DAV:DisplayName?

I suggest you extend the documentation to state that  matchname is matched towards the displayname. If matchname is present, then both matchurl and matchname must match.

**Comment by dilyanpalauzov** [comment]
> I suggest you extend the documentation to state that matchname is matched towards the displayname. I

towards `DAV:displayname`.

**Comment by mstilkerich** [comment]
So you got it working now? matchurl and matchname work as filters on the total set of addressbooks of the specified preset. In the end, exactly one addressbook must remain after filtering. If there is only one addressbook in the preset you don‘t need any filter at all. In your case you will need matchurl, but not matchname, so simply omit the latter.

matchname matches on the addressbook name as stored in rcmcarddav. It can be the serverside displayne, but doesn’t have to, depending on configuration.

**Comment by dilyanpalauzov** [comment]
> So you got it working now? 

Yes.  Thank you very much for all the information.  It was hard to do all settings correctly, but at the end I managed it.

Is there an option to let the user to select the “Collected Recipients” and “Trusted Senders” addressbooks, but do not offer for selection the interal SQL addressbooks?  That is the user can select only CardDAV (or in theory RW-LDAP) addressbooks for collected recipients/trusted senders?

**Comment by mstilkerich** [comment]
I'm not aware of a possibility to specifically exclude addressbooks from these settings if they are available, but you can disable the roundcube SQL addressbook completely if you do not want your users to use it, and then it will also not appear in these config options.

This is done in the roundcube configuration:

```php
// This indicates which type of address book to use. Possible choices:
// 'sql' - built-in sql addressbook enabled (default),
// ''    - built-in sql addressbook disabled.
//         Still LDAP or plugin-added addressbooks will be available.
//         BC Note: The value can actually be anything except 'sql', it does not matter.
$config['address_book_type'] = '';
```

**Comment by mstilkerich** [comment]
Btw please also mind that setting the special addressbooks via admin preset will disallow the user from changing the setting.  The user can change it, but RCMCardDAV will always override the choice of the user as long as the admin setting is enabled. See the corresponding remarks in ADMIN_SETTINGS.md.

I tried to improve the docs a bit regarding the match filter settings.

**Comment by dilyanpalauzov** [comment]
My reading is that `$config['address_book_type'] = '';` disables the internal “Collected Recipients” and “Trusted Senders” SQL-based addressbooks.  With that property set to `''` I open Settings → Contacts.  Under collected addresses there are still shown: for collected recipients: the CardDAV books, the book '-' and 'Collected Recipients'.  My reading is that this addresbook is still offered in SQL backend, despite having set `$config['address_book_type'] = '';`.  For “Trusted Senders” the options are the carddav books, and “Trusted Senders”.  Here again I think that roundcube offers under ”Trusted Senders” a SQL-based addressbook. 

Does your last comment mean, that once plugins/carddav/config.inc.php contains:
```
$prefs['_GLOBAL']['collected_recipients'] = [
    'preset'  => 'CardDAV',
    'matchurl' => '#http://127.0.0.4/dav/addressbooks/user/%l/Default/#',
];
$prefs['_GLOBAL']['collected_senders'] = [
    'preset'  => 'CardDAV',
    'matchurl' => '#http://127.0.0.4/dav/addressbooks/user/%l/Default/#',
];
```
it does not matter what the user selects and by adding `$config['dont_override'] = ['collected_recipients', 'collected_senders'];` the user cannot make choices anymore?

With the changes in https://github.com/mstilkerich/rcmcarddav/blob/master/doc/ADMIN-SETTINGS.md:
```
matchname matches on the addressbook name as stored in RCMCardDAV and shown in the settings interface. When matchname is used, the name attribute should be added to the fixed attributes to prevent the user from changing it. Otherwise, the user could change it to an arbitrary name that the matchname filter might not match anymore.
```
For me this means that `matchname` is matched practically with DAV:displayname, when the name attribute is in `fixed`.  In this case DAV:displayname shall be mentioned explicitly in the above paragraph.

**Comment by dilyanpalauzov** [comment]
> For me this means that matchname is matched practically with DAV:displayname, when the name attribute is in fixed. In this case DAV:displayname shall be mentioned explicitly in the above paragraph.

I see now that the name used by roundcube can be set based on a template, with %N, %D, %c, %k, %a.  It is now more clear for me that the name can be many things.

I think everything here has been clarified.
