### ISSUE TITLE
PHP81 Error : mb_strtolower()

### ISSUE THREAD

**Issue by DA4PKol** [mstilkerich/rcmcarddav#410]
Hello,
Running rcmcarddav 4 (stable, installed with composer) with roundcubemail 1.6 behind nginx and php81-fpm (Rocky Linux 9, remi repo) gives this error :

`PHP Fatal error:  Uncaught TypeError: mb_strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/roundcubemail/program/lib/Roundcube/rcube_addressbook.php:871
Stack trace:
#0 /var/www/roundcubemail/program/lib/Roundcube/rcube_addressbook.php(871): mb_strtolower()
#1 /var/www/roundcubemail/plugins/carddav/src/Addressbook.php(1776): rcube_addressbook->compare_search_value()
#2 /var/www/roundcubemail/plugins/carddav/src/Addressbook.php(344): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->checkPostSearchFilter()
#3 /var/www/roundcubemail/program/actions/contacts/search.php(131): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->search()
#4 /var/www/roundcubemail/program/actions/contacts/search.php(34): rcmail_action_contacts_search::contact_search()
#5 /var/www/roundcubemail/program/include/rcmail.php(275): rcmail_action_contacts_search->run()
#6 /var/www/roundcubemail/index.php(278): rcmail->action_handler()
#7 {main}
  thrown in /var/www/roundcubemail/program/lib/Roundcube/rcube_addressbook.php on line 871`

Downgrading to php74-fpm fix the issue.

Best,

DA4PKol

**Comment by DA4PKol** [comment]
Sorry, I’ve forgotten to say : the error happens when performing a research on the carddav address book.
DA4PKol

**Comment by mstilkerich** [comment]
Thanks for reporting this issue. It happens when the address field of a contact is searched during the search. The same bug appears to exist in roundcube's internal addressbook.

**Comment by mstilkerich** [comment]
Version 4.4.5 with fix for this released.
