### ISSUE TITLE
DB Error on 4.4.6 - Fix included 

### ISSUE THREAD

**Issue by doktoil-makresh** [mstilkerich/rcmcarddav#416]
Hi,

I installed carddav v4.4.6 from tarball into my RoundCube 1.4.13
I previously used carddav version 3.0.3.

Since this migration, I'm seeing the following error in roundcube logs:
[15-Jan-2023 12:49:06 +0100]: <bk46b3m4> DB Error: [1292] Incorrect datetime value: '1673783645' for column `roundcube`.`carddav_addressbooks`.`last_updated` at row 1 (SQL Query: UPDATE carddav_addressbooks SET `last_updated`='1673783645'  WHERE ((`id` = '4'))) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 544 (GET /?_task=addressbook)

The roundcube.carddav_addressbooks table is hosted on a MariaDB server version 10.5.18-MariaDB-0+deb11u1
here is a description of the table:
MariaDB [roundcube]> desc carddav_addressbooks;
+-----------------------+---------------------+------+-----+---------------------+----------------+
| Field                 | Type                | Null | Key | Default             | Extra          |
+-----------------------+---------------------+------+-----+---------------------+----------------+
| id                    | int(10) unsigned    | NO   | PRI | NULL                | auto_increment |
| name                  | varchar(255)        | YES  |     | NULL                |                |
| username              | varchar(255)        | YES  |     | NULL                |                |
| password              | varchar(255)        | YES  |     | NULL                |                |
| url                   | varchar(255)        | YES  |     | NULL                |                |
| active                | tinyint(3) unsigned | NO   |     | 1                   |                |
| user_id               | int(10) unsigned    | NO   | MUL | NULL                |                |
| last_updated          | timestamp           | NO   |     | 2000-01-01 00:00:01 |                |
| refresh_time          | time                | NO   |     | 01:00:00            |                |
| sync_token            | varchar(255)        | YES  |     | NULL                |                |
| authentication_scheme | varchar(64)         | YES  |     | NULL                |                |
| presetname            | varchar(255)        | YES  |     | NULL                |                |
| use_categories        | int(11)             | NO   |     | 0                   |                |
+-----------------------+---------------------+------+-----+---------------------+----------------+

To fix the error, I had to manually apply  dbmigrations/0014-unifytimestampdefaultvalue/mysql.sql against my roundcube.carddav_addressbooks

**Comment by mstilkerich** [comment]
Hi,

  if I understand you correctly, the migration script coming with rcmcarddav worked for you without modification. Normally, rcmcarddav should execute these scripts automatically on user login, so I wonder why you had to execute it manually.

Just to be sure:
  - After the upgrade, did you login and still see these errors?
  - Is there any errors in the carddav.log file? If a migration fails, it should log an error (unless you disabled logging by configuration)
  - What is the content of the carddav_migrations table?

These migrations should be run in sequence and the carddav_migrations table will record which ones have already been applied. Your schema above still shows the authentication_scheme column, which is dropped with migration 0009. Now if you just applied migration 0014, you are missing a few, and problems can arise if you run these scripts not in the intended order.

**Comment by doktoil-makresh** [comment]
As per my reading and understanding of the README.md file, there is no manual operation to perform while migrating from 3.X to 4.4.6, hence I did nothing initially.
After logging in, I did not receive any error from the RC interface. While investigating another plugin issue, I found the log I mentioned in my original message.

From carddav.log, I can't find anything useful.

```
MariaDB [roundcube]> select * from carddav_migrations;
+----+-----------------------------------------+---------------------+
| id | filename                                | processed_at        |
+----+-----------------------------------------+---------------------+
|  1 | 0000-dbinit                             | 2017-08-24 17:16:02 |
|  2 | 0000-sample                             | 2017-08-24 17:16:02 |
|  3 | 0001-categories                         | 2017-08-24 17:16:02 |
|  4 | 0002-increasetextfieldlengths           | 2017-08-24 17:16:03 |
|  5 | 0003-fixtimestampdefaultvalue           | 2017-08-24 17:16:03 |
|  6 | 0004-fixtimestampdefaultvalue           | 2017-08-24 17:16:03 |
|  7 | 0005-changemysqlut8toutf8mb4            | 2019-08-29 15:46:22 |
|  8 | 0006-rmgroupsnotnull                    | 2023-01-15 13:14:10 |
|  9 | 0007-replaceurlplaceholders             | 2023-01-15 13:14:10 |
| 10 | 0008-unifyindexes                       | 2023-01-15 13:14:10 |
| 11 | 0009-dropauthschemefield                | 2023-01-15 13:14:10 |
| 12 | 0010-increasetextfieldlengths           | 2023-01-15 13:14:10 |
| 13 | 0011-unifymigrationsidcolumn            | 2023-01-15 13:14:10 |
| 14 | 0012-fixmysqlconstraints                | 2023-01-15 13:14:14 |
| 15 | 0013-changemysqlcollationscasesensitive | 2023-01-15 13:14:15 |
+----+-----------------------------------------+---------------------+
15 rows in set (0,004 sec)
```
FYI, I had a password issue, and during this period I also received these logs:
[15-Jan-2023 13:18:56 +0100]: <bk46b3m4> [5 ERR] Errors occurred during the refresh of addressbook 4: Exception: Expected Multistatus HTTP request was not successful (401 Unauthorized): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden</s:exception>
  <s:message/>
  <o:hint xmlns:o="o:">password login forbidden</o:hint>
</d:error>
 in /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php:491
Stack trace:
#0 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(507): MStilkerich\CardDavClient\CardDavClient::assertHttpStatus()
#1 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(437): MStilkerich\CardDavClient\CardDavClient::checkAndParseXMLMultistatus()
#2 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/WebDavResource.php(142): MStilkerich\CardDavClient\CardDavClient->findProperties()
#3 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/WebDavResource.php(127): MStilkerich\CardDavClient\WebDavResource->refreshProperties()
#4 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/WebDavCollection.php(110): MStilkerich\CardDavClient\WebDavResource->getProperties()
#5 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/WebDavCollection.php(58): MStilkerich\CardDavClient\WebDavCollection->supportsReport()
#6 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(94): MStilkerich\CardDavClient\WebDavCollection->supportsSyncCollection()
#7 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(57): MStilkerich\CardDavClient\Services\Sync->synchronizeOneBatch()
#8 /usr/share/roundcube/plugins/carddav/src/Addressbook.php(1245): MStilkerich\CardDavClient\Services\Sync->synchronize()
#9 /usr/share/roundcube/plugins/carddav/carddav.php(1581): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->resync()
#10 /usr/share/roundcube/plugins/carddav/carddav.php(439): carddav->resyncAddressbook()
#11 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(469): carddav->getAddressbook()
#12 /usr/share/roundcube/program/include/rcmail.php(226): rcube_plugin_api->exec_hook()
#13 /usr/share/roundcube/program/steps/addressbook/func.inc(152): rcmail->get_address_book()
#14 /usr/share/roundcube/program/steps/addressbook/func.inc(102): rcmail_contact_source()
#15 /usr/share/roundcube/index.php(284): include_once('/usr/share/roun...')
#16 {main} 
[15-Jan-2023 13:27:07 +0100]: <bk46b3m4> [5 ERR] sync-collection REPORT produced exception {"exception":{}}

Please note that since, I appears the carddav plugin tries to perform some migration steps:
[15-Jan-2023 14:36:41 +0100]: <k7ii60d0> [5 ERR] Migration query (ALTER TABLE carddav_addressbooks ADD `last_updated_ts` BIGINT NOT NULL DEFAULT 0 AFTER `last_updated`;) failed: [1060] Duplicate column name 'last_updated_ts' 
[15-Jan-2023 14:38:15 +0100]: <of81e9ob> [5 ERR] Migration query (ALTER TABLE carddav_addressbooks ADD `last_updated_ts` BIGINT NOT NULL DEFAULT 0 AFTER `last_updated`;) failed: [1060] Duplicate column name 'last_updated_ts'

**Comment by mstilkerich** [comment]
Hello,

  from the information you share it looks like something is seriously broken with the carddav tables:
- Your migration scripts show that all up to migration 13 has been performed, but your carddav addressbooks table you shared in the first post contains a column that should not exist from migration 9 anymore.
- The last_updated_ts column is a temporary column that is created and removed (by renaming it to last_updated) in migration 14. I assume your manual run did not produce any errors (since you didn't say it did), but you did not record the run in the migrations table. So now on every login, rcmcarddav will try to execute migration 14, and my guess is that the first attempt had an error in the middle of the script, leaving the last_updated_ts column in place, and now you are getting these errors on every login.

So at this point, you need to manually clean up, or drop the carddav_* tables and start over. I don't know how large your installation is, i.e., if dropping the tables will be an issue or not for your installation. But it would be the simplest solution to return to a clean state.

If you want to clean up, you have to make sure to reverse all the intermediate changes performed by migration 14, and then add that migration to carddav_migrations table yourself, since you already executed it by hand. Then on next login, rcmcarddav will execute migrations 15 and 16 and unless there are any errors left over in the DB, you should be good again. In INIT-currentschema/mysql.sql, you can see what the final DB schema for your rcmcarddav release should look like.

Concerning the upgrade notes, maybe I should be clearer on that you have to login freshly after upgrading rcmcarddav, because database schema will only be checked and upgraded during the login process. Checking the schema on every request would create a lot of unneccessary DB requests. I thought it was in the docs, but apparently not.

**Comment by doktoil-makresh** [comment]
Thank you for your explanations and detailed steps.
Inserting the missing step (0014) into the table seems to do the trick:
```
nsert into carddav_migrations values (16,'0014-unifytimestampdefaultvalue','2023-01-15 13:20:15');
MariaDB [roundcube]> select * from carddav_migrations;
+----+-----------------------------------------+---------------------+
| id | filename                                | processed_at        |
+----+-----------------------------------------+---------------------+
|  1 | 0000-dbinit                             | 2017-08-24 17:16:02 |
|  2 | 0000-sample                             | 2017-08-24 17:16:02 |
|  3 | 0001-categories                         | 2017-08-24 17:16:02 |
|  4 | 0002-increasetextfieldlengths           | 2017-08-24 17:16:03 |
|  5 | 0003-fixtimestampdefaultvalue           | 2017-08-24 17:16:03 |
|  6 | 0004-fixtimestampdefaultvalue           | 2017-08-24 17:16:03 |
|  7 | 0005-changemysqlut8toutf8mb4            | 2019-08-29 15:46:22 |
|  8 | 0006-rmgroupsnotnull                    | 2023-01-15 13:14:10 |
|  9 | 0007-replaceurlplaceholders             | 2023-01-15 13:14:10 |
| 10 | 0008-unifyindexes                       | 2023-01-15 13:14:10 |
| 11 | 0009-dropauthschemefield                | 2023-01-15 13:14:10 |
| 12 | 0010-increasetextfieldlengths           | 2023-01-15 13:14:10 |
| 13 | 0011-unifymigrationsidcolumn            | 2023-01-15 13:14:10 |
| 14 | 0012-fixmysqlconstraints                | 2023-01-15 13:14:14 |
| 15 | 0013-changemysqlcollationscasesensitive | 2023-01-15 13:14:15 |
| 16 | 0014-unifytimestampdefaultvalue         | 2023-01-15 13:20:15 |
| 17 | 0015-fixmysqlconstraints                | 2023-01-15 19:23:27 |
| 18 | 0016-increasetextfieldlengths           | 2023-01-15 19:23:27 |
+----+-----------------------------------------+---------------------+

```

**Comment by mstilkerich** [comment]
Ok, great!
Is there any issue left or can we close this issue?

**Comment by doktoil-makresh** [comment]
No issue left, as far as I can see ;)
