### ISSUE TITLE
Add addressbook to Preset account

### ISSUE THREAD

**Issue by neilromig** [mstilkerich/rcmcarddav#420]
Setup: Arch Linux, roundcube 1.6.0, rcmcarddav 5.0.1, radicale 3.1.8

I have configured carddav plugin with preset values for the user:

`$prefs['_GLOBAL']['collected_recipients'] = [
    'preset' => 'Personal',
    'matchurl' => '#https://myserver.com/%l/#',
];
$prefs['_GLOBAL']['collected_senders'] = [
    'preset' => 'Personal',
    'matchurl' => '#https://myserver.com/%l/#',
];
$prefs['Personal'] = [
    'accountname' => 'Personal',
    'username' => '%l',
    'password' => '%p',
    'discovery_url' => 'https://myserver.com/%l/',
    'active' => true,
    'readonly' => false,
    'refresh_time' => '02:00:00',
    'fixed' => ['username','password'],
    'hide' => false,
];
`

However I cannot find a way to add an addressbook to this account - only options visible are to create another account, or to perform rediscovery.
Am I missing something or is it not possible to add a CARDDAV addressbook using roundcube?

Neil.

**Comment by mstilkerich** [comment]
Hello, what exactly do you mean by „add an addressbook to the account“? It is not currently possible to create new addressbooks on the CardDav server with rcmcarddav. It will discover the existing addressbooks on the server automatically. In special cases where this is not possible (e.g. public addressbooks outside the addressbook home of the user), you can explicitly specify these as `extra_addressbooks`.

**Comment by neilromig** [comment]
Thanks for the answer. It was a new addressbook within the CARDDAV account I wanted, so will have to create with Radicale's web interface.
