### ISSUE TITLE
Not working RC 1.6.1

### ISSUE THREAD

**Issue by KoRn0509** [mstilkerich/rcmcarddav#423]
not working RC 1.6.1 upd pls

**Comment by mstilkerich** [comment]
Can you be a bit more precise on what exactly is not working? I am using Roundcube 1.6.1 myself and do not experience issues.

**Comment by KoRn0509** [comment]
error
Database::get (SELECT * FROM carddav_accounts WHERE ((`user_id` = '2'))) ERROR: [1146] Table 'roundcubemail.carddav_accounts' doesn't exist

**Comment by KoRn0509** [comment]
I've reinstalled everything now. Everything worked. Thanks)
