### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by unalignedcoder** [mstilkerich/rcmcarddav#426]
Hi.
This is the first time I install a plugin in roundcube so bear with me,

Following the instructions located [here](https://getcomposer.org/download/), I installed composer, seemingly successfully, in a dedicated folder within the public_html folder where roundcube is also located.

Running `php composer.phar` returns the list of commands with no errors.

Then I ran the command:
`php composer.phar require --update-no-dev -o "roundcube/carddav:*"`

but the installation fails:

`include_once(/home/<username>/domains/<domainname>/composer/program/include/clisetup.php): Failed to open stream: No such file or directory`

I can see that, despite me having installed composer, there is no such 'program' folder anywhere to be seen. Not sure why. The installation returned no errors.

What am I doing wrong?

**Comment by mstilkerich** [comment]
Hello,

 you can put the composer.phar anywhere, I also would not put it in a directory served by the webserver.

Of course when calling composer, you will have to specify the correct path to composer.phar.

The important bit, and I guess this is what you are currently doing wrong, is that you must call composer inside the roundcube installation directory.

**Comment by unalignedcoder** [comment]
All clear, thank you.

But it still fails. It seems it needs the ldap extensions. 

Can I run it with the  `--ignore-platform-req=ext-ldap` argument or is ldap a carddav requirement?

**Comment by mstilkerich** [comment]
It is a roundcube dependency if you want to use the LDAP addressbook. Rcmcarddav does not need it. So the answer is yes. You could also remove it from composer.json.

**Comment by mstilkerich** [comment]
Is this resolved for you?

**Comment by unalignedcoder** [comment]
Yes, I installed, thank you. Now there's the problem that it won't recognize any of the Nextcloud links I am trying to open. But that's for another thread I guess
