### ISSUE TITLE
Gmail still supported

### ISSUE THREAD

**Issue by righter83** [mstilkerich/rcmcarddav#427]
Hi

is the plugin still working with the newest version?
Is there a complete guide how to configure it?

**Comment by mstilkerich** [comment]
Yes it should. You need to use an application specific password that you can create in your google account settings. As url you can simply use gmail.com.

Alternative is using Oauth, but this only makes sense if you also want to login to roundcube using google and access google mail account.

**Comment by mstilkerich** [comment]
Is there any specific problem you need help with? Otherwise I will close the issue.

**Comment by righter83** [comment]
Ok I tried to use Oauth2 which wasnt working.
Maybe you could the how to for Gmail in the docs:

GMail Settings:
- Open Google Account -> https://myaccount.google.com
- Go to Security -> App-Passwords
- App=Contacts / Device=Other -> Generate -> Name=Roundcube -> Then you see the App-Password

Rouncube CardDAV Settings:

- Name: Google
- URL: google.com
- Username: your gmail address
- Password: App-Password from above
- Keep the other settings on default

**Comment by mstilkerich** [comment]
OAuth2 requires a more extensive setup by the admin, including registration of their roundcube installation as an App with Google. For an individual user, app-specific passwords is the proper and simple solution.

Amendment to your instructions: You must use `gmail.com` (or `googlemail.com`) for URL, I don't think that `google.com` will work. The latter is for google employees and also advertises a CardDAV service, but I would assume a different one than that of gmail. Did not try though.
