### ISSUE TITLE
[Enhancement] Add a script to force preset rediscovery for any user

### ISSUE THREAD

**Issue by DoobleD** [mstilkerich/rcmcarddav#428]
First of all, thank you for this plugin, it's working like a charm. This is not an issue, just an enhancement idea.

It'd be neat to have a script/tool to force the rediscovery of a given preset for any given user. Perhaps something looking like:

```
php ./scripts/rediscover.php <preset_name|account_name> <username>
```

We handle a DAV server and a Roundcube webmail, and when people create/edit/delete an address book on our DAV server, we'd like to trigger a CardDAV rediscovery in Roundcube for the corresponding preset and user. Rather than relying on `rediscover_time`, which requires a logout/re-login action from the user.

Disclaimer: I have no idea how hard it would be to make that script.

**Comment by mstilkerich** [comment]
It is probably not too difficult to write the script, but it will only work if the CardDav password of the user is available. When the `encrypted` password store scheme is used, the user‘s IMAP password is needed to decrypt the stored Carddav password. Second case is when the `%p` placeholder is used, which I guess is quite common in preset setups. Also here the Imap password is needed, which is also the carddav password in that case.

**Comment by DoobleD** [comment]
Thank you for the prompt reply @mstilkerich!

That makes sense. We don't have access to the unencrypted password and I don't see any secure way around that, so I'll close the thread. Anybody feel free to reopen if needed!
