### ISSUE TITLE
Add require_always_email for all carddav

### ISSUE THREAD

**Issue by pboesch** [mstilkerich/rcmcarddav#429]
Hello!

I have recently adding carddav plugin on rouncdube 1.6. I have added, throught web interface, a nextcloud carddav url. I don't have create `config.inc.php`. All contacts have been synchronize. I'm looking for to hide contacts without email. 

So I've tried to create and add in `config.inc.php` :
```
 $prefs['_GLOBAL']['require_always_email'] = true;
```

Or:
```
$prefs['nextcloud'] = [
    'accountname'  =>  'Contacts',
    'require_always_email' => true,
];
```
Clear cache and re-sync. But all contacts appears again.

Is the only solution is to create the entire carddav configuration in `config.inc.php`? If so, how to avoid the password to appear in it?

Thank you

**Comment by mstilkerich** [comment]
Hello, this option is currently only available for admin presets. It cannot be set as a global option. I can add it as a option to the UI so that it can also be set for user-defined addressbooks.

**Comment by pboesch** [comment]
Ok thanks for explanation. I don't know for others,but I think it would be nice if this option was available on the UI.

**Comment by mstilkerich** [comment]
Feature is available on master branch
