### ISSUE TITLE
read config from roundcube global config instead of local plugin folder

### ISSUE THREAD

**Issue by kaystrobach** [mstilkerich/rcmcarddav#430]
for ease of deployment it would be perfect to get rid of the config.inc.php in the pluginfolder, but load the config from the global config of roundcube. If you are interested in this change i can let my team do that.

**Comment by mstilkerich** [comment]
Hello,

 it is the standard way for roundcube plugins to come with their own `config.inc.php` file, even the plugins included with roundcube core do not put their configuration options in the roundcube main config but use their own config file. Therefore, I would like to keep it as.

**Comment by kaystrobach** [comment]
Ok, i get your point. Will ask in the RC repo. The problem i see with that approach is a cluttered config and also a possible lost config with a composer update.

thank you and have a nice day
