### ISSUE TITLE
Auto-synchro cloud addressbooks using app-password token.

### ISSUE THREAD

**Issue by quenenni** [mstilkerich/rcmcarddav#433]
I think I found all the problems I had to my attempt to use a app-password token to auto-connect the clouds addressbooks to the roundcube.

I updated my test cloud to v25, so it's not anymore with that old Nextcloud version.

My first problem was the uppercases lost in the login when used in this plugin. Nextcloud is case sensitive for the login.
I switched to use the mail as login as Nextcloud accepts it also.
But then I had my 5 min lifetime token and nothing was working anymore after 5 min.

I finally found the reason behind that error.
After 5 min, there is a new authentication check on Nextcloud side and the cloud is not happy and refuse to accept the authentication.

The log msg I found for this:
```
{"reqId":"U3GJMkHkYgkYHeP5VPYo","level":3,"time":"April 14, 2023 14:57:28","remoteAddr":"111.222.333.444","user":"--","app":"no app in context","method":"PROPFIND","url":"/remote.php/dav","message":"App token login name does not match","userAgent":"GuzzleHttp/6.5.5 curl/7.74.0 PHP/8.0.13","version":"25.0.5.1","data":{"tokenLoginName":"quenenni","sessionLoginName":"[quenenni@YYYY.coop](mailto:quenenni@YYYY.coop)"}}
```

From my understanding, there is a mix between the login used in the new authentication process (the login version) and the one already redistered in session (the mail version).
But I have no clue where, why or how it is done.

So I went back to use the login and not the mail as login for Nextcloud to check and indeed, it's working nicely without time limitation... All is good.. Except I came back to my old problem.

The cases where the login is all lowercase, like xyz as login and the associated mail is xyz@yyyy.coop, the system works nicely.
But for cases like when the users have Xyz as login (with one or more uppercases letters) and xyz@yyyy.coop as mail, the used login for Nextcloud is not good.

Your plugin, when we are using the substitution '%l' in the config file takes the first part of the mail (before the @) and use it as login.

I'm trying to adapt it in order to find the right case sensitive login from the bearer token.
It should contain the preferred_username attribute that contains the case sensitive login. 

I can get the token in the plugin context:
```
        $rcube = rcube::get_instance();
        $bearertoken = $rcube->decrypt((string) $_SESSION['password']);
```

But I don't know how to decrypt it in order to see the data inside.
Would you know how to do it?

Thanks

**Comment by mstilkerich** [comment]
Checkout `$_SESSION['oauth_token']`. I can’t remember the exact format, but roundcube stores the token there. Best simply dump the contents of the variable to see the format.

**Comment by quenenni** [comment]
Thanks for your help.

Indeed, we  can retrieve the access token in clear format with `$_SESSION['oauth_token']['access_token']`

 `$bearertoken = $rcube->decrypt((string) $_SESSION['password']);` works too.

What I was looking for is how to decrypt it using roundcube code.
I found the function `jwt_decode` in the class rcmail_oauth (from `program/include/rcmail_oauth.php`) that does exactly that.

I added a new custom substitution for the username field -> %z

And in the function replacePlaceholdersUsername I changed to:
```
    private static function replacePlaceholdersUsername(string $username): string
    {   
        $rcube = rcube::get_instance();
        $rcusername = (string) $_SESSION['username'];
        $accesstoken = (string) $_SESSION['oauth_token']['access_token'];

        if (!($accesstoken === false || strlen($accesstoken) == 0)) {
            $oauth = rcmail_oauth::get_instance();
            $body = $oauth->jwt_decode($accesstoken);
            $tokenusername = $body['sub'];
        }

        $username = strtr($username, [
            '%u' => $rcusername,
            '%l' => $rcube->user->get_username('local'),
            '%d' => $rcube->user->get_username('domain'),
            // %V parses username for macosx, replaces periods and @ by _, work around bugs in contacts.app
            '%V' => strtr($rcusername, "@.", "__"),
            '%z' => $tokenusername
        ]);

        return $username;
    }
```
And it is working now with login with uppercase letters.

In my case, I used the 'sub' attribute from the access token.
I'm not sure though if it's a good idea to use that sub attribute or to get the attribute from the scope, like `preferred_username` or any other that is in the scope.

Maybe a way to generalyse this is to have a new config option for when using the username substitution '%z' like `'usernametokenfield' => '<preferred_username>'

But i don't know how to request the value of an attribute from the scope.
Do I have to request it to my Idp or can I find it somewhere in roundcube context.

```
$config['oauth_scope'] = "email profile openid";
$config['oauth_identity_fields'] = ['email', 'preferred_username'];
```

I need to do more tests, but I feel confident this problem is fixed.

**Comment by quenenni** [comment]
Seems to work nicely.
I'll make another issue (feature request) when I'll have tested successfully my code on the last version of the plugin.
