### ISSUE TITLE
Is two way sync supported?

### ISSUE THREAD

**Issue by AuspeXeu** [mstilkerich/rcmcarddav#438]
I have this plugin connected to my Nextcloud address books and I was wondering whether changes on roundcube will eventually be synchronised back to NC's carddav server?

**Comment by mstilkerich** [comment]
Yes, actually the changes will be done directly on the server side and then synced back to roundcube. The database in roundcube is mostly a cache, it does not change independently of the server.

**Comment by AuspeXeu** [comment]
Never mind, this was totally my fault. I changed `firstname` but there was still a differnt `display name` set for the contact. Works like intended. Thanks for the plugin and your help!
