### ISSUE TITLE
Make default_addressbook settable from a preset like other special addressbooks

### ISSUE THREAD

**Issue by TCB13** [mstilkerich/rcmcarddav#440]
Hello,

Thank you very much for this amazing plugin.

As suggested here https://github.com/mstilkerich/rcmcarddav/issues/372#issuecomment-1006863280 set this `$config['address_book_type'] = '';` in order to disable the built in address book of RC.

After loading the UI on the contacts section I get no contacts at all:

![Screenshot 2023-05-08 185728](https://user-images.githubusercontent.com/6315832/236896268-c067bb51-7929-4b43-8bd5-f4cacb7b204d.jpg)

I believe this happens because collected addresses appear first on the address book list:

![Screenshot 2023-05-08 185241](https://user-images.githubusercontent.com/6315832/236896582-d0ee6145-e7da-4352-a44e-9ec3a4547de2.jpg)

Is there a way to make sure my DAV **default** address book appears before the others? This obviously is manageable to me but I've a few less tech savvy family members that will never figure that out and will simply assume there are no contacts.

Thank you.

**Comment by mstilkerich** [comment]
Hi, this list is created by roundcube and I do not know if / how it is sorted and whether it can be influenced by rcmcarddav. Rcmcarddav just provides a list of carddav addressbooks to roundcube with no particular order.

However, normally roundcube will automatically select the default addressbook configured by the user. I have configured a carddav addressbook as my default and when I open the contacts pane, it will always be initially selected although it is not first in the list.

**Comment by mstilkerich** [comment]
Yes, that is what I mean by every user has to configure it.

The `default_addressbook` option must be set to an addressbook ID, e.g. `carddav_1`. However, the number is the database ID of the CardDAV addressbook and it is different for every addressbook. That's why it is not currently possible for the admin to configure it.

This config option is similar to `collected_recipients` and `collected_senders`, for which I already implemented a way for the admin to set them to carddav addressbooks based on matches against URL or name of the addressbook. It should be straightforward to also enable it for `default_addressbook`, I just was not aware of the option.

**Comment by TCB13** [comment]
Well, I'm not sure if I'm missing the point or if this feature isn't working. I tried to setup this like:

````
$prefs['_GLOBAL']['default_addressbook'] = [
    'preset'  => 'main',
    'matchurl' => '#https://server.example.org/dav/dav.php/addressbooks/%u/default/#',
];
````

And what happens is that under RC > Contacts I still don't get the `default` address book called `Address Book` selected by default:

![image](https://github.com/mstilkerich/rcmcarddav/assets/6315832/31f7edc2-ba40-42b1-aacd-ffef0557a0b0)

For reference, here is the setup of the address book in Baikal:

![image](https://github.com/mstilkerich/rcmcarddav/assets/6315832/da46ec7e-054b-4201-8c70-11b04ffc5d95)

**Comment by mstilkerich** [comment]
Is there anything in carddav.log? Does the addressbook show up as the default_addressbook in the roundcube settings?

Regarding the matchurl setting, it must contain a regular expression and therefore have the delimiters, so yes the # (or any other valid delimiter character) is needed. When the preset only contains a single addressbook you can also omit the matchurl and matchname settings.

**Comment by TCB13** [comment]
> Is there anything in carddav.log?

Apparently it does:

````
[29-Sep-2023 11:23:33 +0100]: <5p6kb994> [5 ERR] Cannot set special addressbook default_addressbook, there are 0 candidates (need: 1) 
[29-Sep-2023 11:23:38 +0100]: <5p6kb994> [5 ERR] Cannot set special addressbook default_addressbook, there are 0 candidates (need: 1) 
[29-Sep-2023 11:23:38 +0100]: <5p6kb994> [5 ERR] Cannot set special addressbook default_addressbook, there are 0 candidates (need: 1) 
````

> Does the addressbook show up as the default_addressbook in the roundcube settings?

I believe so. But that happens even without the plugin enabled:

![image](https://github.com/mstilkerich/rcmcarddav/assets/6315832/a5c0125e-7494-461e-95c7-706367131d8e)

> When the preset only contains a single addressbook you can also omit the matchurl and matchname settings.

In this case there's always an Address Book called "default" and user might add others, I would like it to default do the "default" one.

> Also which roundcube version do you use?

RC 1.6.0

Thank you.

**Comment by mstilkerich** [comment]
Please do not set default_addressbook in the roundcube config. Not that it really matters in case rcmcarddav overrides it, but it case it fails the value you set there makes no sense as it’s no valid addressbook id.

As to why it does not match I cannot tell. It looks good to be but there are parts that are blurred. l

Maybe try simpler if the last component of the url is always `default`:

```php

$prefs['_GLOBAL']['default_addressbook'] = [
    'preset'  => 'main',
    'matchurl' => '#/default/$#',
];
```

Please check the URL for the addressbook shown in the carddav settings, the match is applied to the URL as shown there. Simple things like presence or absence of a trailing slash could cause the match to fail. Also mind that matchurl is a regex and certain characters carry a special meaning.
