### ISSUE TITLE
Settings panel doesn't load?

### ISSUE THREAD

**Issue by RobinBoers** [mstilkerich/rcmcarddav#445]
Hi, I tried installing this plugin in a docker container running the latest roundcube release. The settings panel appears in the roundcube settings, but when I try to open it I get this error: 

> FILE NOT FOUND
> The requested resource was not found!
> Please contact your server-administrator.
> 
> Failed request: localhost:4200/?_task=settings&_action=plugin.carddav

![image](https://github.com/mstilkerich/rcmcarddav/assets/60298132/793d7d7a-a939-4343-99a6-2ae28f965b34)

I tried to reinstall the plugin and to disable and enable it again, but that didn't seem to work :/

**Comment by mstilkerich** [comment]
Anything in the roundcube log?

**Comment by RobinBoers** [comment]
I get this in the Roundcube logs:

```
roundcubemail  | errors: <1e58d61f> PHP Error: Error loading template for carddav.addressbooks in /var/www/html/program/include/rcmail_output_html.php on line 804 (GET /?_task=settings&_action=plugin.carddav)
roundcubemail  | 172.26.0.1 - - [01/Jul/2023:17:26:14 +0000] "GET /?_task=settings&_action=plugin.carddav HTTP/1.1" 200 5024 "http://localhost:4200/?_task=settings" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0"
```

I installed the plugin by running `docker exec -it <container_id> /bin/bash`:

```bash
root@968730bd5dfd:/var/www/html# composer require --update-no-dev -o "roundcube/carddav:*"
```

**Comment by mstilkerich** [comment]
Do you use a non-standard roundcube skin?

**Comment by RobinBoers** [comment]
Yes, I was using a modified version of elastic (https://github.com/vfosnar/roundcube-protonmail-skin). Switching back to default elastic solves the problem. Thanks!
