### ISSUE TITLE
"Internal Error" in Contacts upon reload

### ISSUE THREAD

**Issue by dranelixx** [mstilkerich/rcmcarddav#446]
When attempting to reload the contact page, an “Internal Error” is encountered, and the following error log is generated:

```
[18-Jul-2023 08:18:06 Europe/Berlin] PHP Deprecated: Creation of dynamic property vcard_attach::$template is deprecated in /web/rc/plugins/vcard_attach/vcard_attach.php on line 40
[18-Jul-2023 08:18:06 Europe/Berlin] PHP Fatal error: Uncaught TypeError: Unsupported operand types: string & int in /web/rc/program/lib/Roundcube/rcube_utils.php:303
Stack trace:
#0 /web/rc/plugins/vcard_attach/vcard_attach.php(52): rcube_utils::get_input_value('_source', 'RCUBE_INPUT_GPC')
#1 /web/rc/program/lib/Roundcube/rcube_plugin_api.php(520): vcard_attach->render_page(Array)
#2 /web/rc/program/include/rcmail_output_html.php(828): rcube_plugin_api->exec_hook('render_page', Array)
#3 /web/rc/program/include/rcmail_output_html.php(654): rcmail_output_html->parse('addressbook', false)
#4 /web/rc/program/include/rcmail.php(296): rcmail_output_html->send('addressbook')
#5 /web/rc/index.php(278): rcmail->action_handler()
#6 {main}
thrown in /web/rc/program/lib/Roundcube/rcube_utils.php on line 303
```

Otherwise, the Plugin works fine, so I assume I did install it correctly?

**Expected Behavior:**
The Contacts page should reload successfully without any errors or interruptions.

**Actual Behavior:**
Upon reloading the Contacts page, an "Internal Error" is displayed, preventing users from accessing their contacts. The error log provides further details about the issue.

**Comment by mstilkerich** [comment]
rcmcarddav does not appear in the call trace. Why do you report this issue in this repo? Another non-standard plugin `vcard_attach` shows up in the call trace though.

**Comment by dranelixx** [comment]
Thanks a lot, and sorry for the false issue :)
