### ISSUE TITLE
Just started receiving a 500 http error

### ISSUE THREAD

**Issue by darren12345** [mstilkerich/rcmcarddav#451]
My Carddav is set to sync contacts from my GMail. It's worked until fine until a couple of days ago when I started seeing this error:

```
[15-Aug-2023 20:00:35 +0100]: <0382khmu> [5 ERR] Failed to sync addressbook: Expected Multistatus HTTP request was not successful (500 Internal Server Error): {
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
```

No other entry for today in the logs. Is this an internal Google error?

**Comment by mstilkerich** [comment]
Hi,

  I am also seeing this errors with Basic Authentication. When using OAuth2 everything is working fine.

However, basic authentication is not entirely disabled, some accesses still work fine. It's really weird.

Anyway, it's an issue on Google's end.

**Comment by darren12345** [comment]
Wait, you can use OAuth with carddav and google? I had no idea.

**Comment by mstilkerich** [comment]
Yes, but it means you will have to register your roundcube installation as an application at Google to get a clientid/secret. You do this on google developer console with your Google Account.

Then you have to setup roundcube to use oauth2 via Google. It means login to roundcube will then involve a redirection to Google and you login there.
https://github.com/roundcube/roundcubemail/wiki/Configuration:-OAuth2

For carddav you then simply specify `%b` as password an it will use the bearertoken from roundcube.
