### ISSUE TITLE
Unparenthesized `a ? b : c ? d : e` is not supported

### ISSUE THREAD

**Issue by peter4200** [mstilkerich/rcmcarddav#452]
Just installed this plugin and no nothing is working due to this error:
**[20-Aug-2023 17:25:03 Europe/Copenhagen] PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/roundcube/plugins/carddav/carddav.php on line 352**

Server info:
Ubuntu 22.04 fully updated
PHP 8.1.2-1ubuntu2.13 (cli) (built: Jun 28 2023 14:01:49) (NTS)

**Comment by mstilkerich** [comment]
What version of the plugin have you installed? That line doesn't contain any ternary expression in the current release.

**Comment by peter4200** [comment]
Hmm, I did a **composer require "roundcube/carddav"** as described on the plugin-page at roundcube.net (https://plugins.roundcube.net/#/packages/roundcube/carddav)
I will uninstall v3 and try with a >= 5.0.0

**Comment by mstilkerich** [comment]
Then I guess you have some other plugin installed with a dependency constraint that forces composer to use this very old version of RCMCardDAV.

Try installing with `composer require --update-no-dev -o "roundcube/carddav:~5"` and composer will probably fail and tell you why it cannot install the v5 version.

**Comment by peter4200** [comment]
Correct, composer is failing. Thanks for pointing me in the right direction and sorry for the "noise" :-)
