### ISSUE TITLE
Tries to insert NULL into "cuid"

### ISSUE THREAD

**Issue by sophie-h** [mstilkerich/rcmcarddav#455]
I'm getting a lot of

> null value in column "cuid" of relation "carddav_contacts" violates not-null constraint

In my log. The data source is Nextcloud instance. The cards in the log have

> BEGIN:VCARD\x0d
> VERSION:3.0

But it might be that all replies are in vcard3 if it's not requested explicitly https://github.com/nextcloud/server/issues/12878#issuecomment-552981236

Any idea how to approach debugging this?

**Comment by mstilkerich** [comment]
It sounds like you already found how to enable the debug logging. When debug logging of http communication is enabled, you see the synced vcards inside carddav_http.log. Do all vcards include a UID property? UID property is mandatory for carddav.

If there is a lot of contacts synced and you cannot check all of them, you could also add a check before where storeContact is called in SyncHandlerRoundcube.php that checks if save_data['cuid'] is present and if not creates a log entry with the URI of the card. This you can use to find if there are defective cards sent by the server and which they are. I can provide this code for you if needed.

Version 3 vcards returned by the server should not be related to this issue.

**Comment by mstilkerich** [comment]
No feedback
