### ISSUE TITLE
guzzlehttp/promises/src/functions_include.php missing

### ISSUE THREAD

**Issue by Sailing74** [mstilkerich/rcmcarddav#456]
Hi, trying to update my Roundcube installation from 1.6.1 to 1.6.4, I am getting the below error when trying to update rcmcarddav (via php composer.phar update --no-dev) for this version:

`Package operations: 0 installs, 1 update, 0 removals
    Update of roundcube/carddav failed
  [Deprecation Notices]
  [ErrorException]
  require(/var/www/roundcube/vendor/composer/../guzzlehttp/promises/src/funct
  ions_include.php): Failed to open stream: No such file or directory`

/var/www/roundcube/vendor/guzzlehttp/promises/src/functions_include.php does indeed not exist.

Did I miss something? The upgrade instructions just talk about some admin settings which I am not using, so I didn't do anything else specifically to upgrade rcmcarddav.

Thanks.

**Comment by mstilkerich** [comment]
It's a bug in the roundcube-plugin composer plugin.

See workaround here:
https://github.com/mstilkerich/rcmcarddav/blob/master/doc/INSTALL.md#update-using-composer
