### ISSUE TITLE
PHP Deprecated: Using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by emtiu** [mstilkerich/rcmcarddav#461]
Hi, thanks for your work :)

I'm running Roundcube 1.6.5 on Apache 2.4.58 with PHP 8.2.14. I see many of these warnings in my maillog:
```
roundcube[50776]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /[…]/Roundcube/plugins/carddav/carddav.php on line 589
roundcube[50776]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /[…]/Roundcube/plugins/carddav/carddav.php on line 596
roundcube[50776]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /[…]/Roundcube/plugins/carddav/carddav.php on line 601
roundcube[50776]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /[…]/Roundcube/plugins/carddav/carddav.php on line 981
roundcube[50776]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /[…]/Roundcube/plugins/carddav/carddav.php on line 990
roundcube[50776]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /[…]/Roundcube/plugins/carddav/carddav.php on line 1124
```
I'm happy to provide more info if needed.

**Comment by mstilkerich** [comment]
Hi, I guess you use some older version of rcmcarddav. Please use the current release where this should be fixed.

**Comment by emtiu** [comment]
You're right, the problem is likely with the version I'm using. I thought I was using composer in a way that keeps everything updated, but it seems I was wrong:
```
$ php composer.phar info | grep card
mstilkerich/carddavclient     v1.4.0   CardDAV client library to discover and synchronize with CardDAV se...
roundcube/carddav             v4.4.6   CardDAV adapter for connecting to CardDAV-enabled addressbooks
```
Can you help me get to your current version 5.x.x?

**Comment by emtiu** [comment]
I managed to update :)

For whatever reason, I had `"roundcube/carddav": "^4.1"` in the require section of my composer.json. I changed it to `"roundcube/carddav": ">=5.0"` and was able to update as expected.

After following the update procedure laid out in `README.md`, the warnings are now gone and everythink works well.
