### ISSUE TITLE
Как добавить пользователей в адресную книгу Baikal

### ISSUE THREAD

**Issue by sys-team-59** [mstilkerich/rcmcarddav#465]
Добрый день! Коллеги нужна ваша помощь по настройке Адресной книги в Baikal. Суть вопроса: Адресная книга создана но при создании пользователя я так понял создаётся ещё одна адресная книга. Я так понял что у каждого пользователя создаётся своя адресная книга Но хотелось  чтобы была общая адресная книга. Почтовый клиент использую mozila thunderbird. при синхронизации адресной книги ни одного пользователя нет ? как быть ? Заметил что если добавить в ручную пользователя в адресную книгу и синхронизировать его в Baikal вижу созданного пользователя но как им управлять ? В ручную всех добавлять и синхронизировать в Baikal ? не очень удобно хотелось бы на оборот создавать пользователей в Baikal и синхронизировать в почтовом клиенте. Как быть ? @mstilkerich

**Comment by mstilkerich** [comment]
Not sure if I understand correctly what you want to do. Users for the CardDAV service (e.g. Baikal) have to be created in that service, rcmcarddav cannot do it.

As far as I know, Baikal does not support addressbook sharing among users. If you want a central addressbook accessible by all users, you could create an extra user in Baikal and add the user and the addressbooks belonging to it as an admin preset in rcmcarddav, which would then be available to all users. Users could still have their personal addressbooks in a separate account.

**Comment by sys-team-59** [comment]
Спасибо за помощь @mstilkerich  Разобрасля как работает Baikal адресная книга. Ещё такой вопрос когда я создал адресную книгу в Baikal для синхронизации контактов использую tbsunc caldav carddav возможно ли в почтовом клиенте thunderbird экспортировать все адреса в созданную адресную книгу Baikal или в ручную придётся добавлять адреса ?

**Comment by sys-team-59** [comment]
Добрый день! @mstilkerich  Не подскажите ещё как правильно обновить Baikal ?

**Comment by mstilkerich** [comment]
Hello, these question are not related to RCMCardDAV. I don't use thunderbird and cannot tell you how to migrate your contacts from the thunderbird addressbook to Baikal. I also cannot help you with upgrade instructions for Baikal, please see the Baikal documentation. Please mind: this is an issue tracker for RCMCardDAV.
