### ISSUE TITLE
Добавление адресной книги carddav в rouncube

### ISSUE THREAD

**Issue by sys-team-59** [mstilkerich/rcmcarddav#466]
Помогите добавить адресную книгу. По инструкции установил doc/ADMIN-SETTINGS.md.
Версия rouncube 1.6.1
версия carddav 4.4.6
ошибка в логах пишет,  54,56,57 строчка  /var/www/roundcube/plugins/carddav/config.inc.php
что нужно указать carddav/config.inc.php прописать путь к адресной книге и её название ? 
/var/www/roundcube/plugins/carddav/config.inc.php (Конфигурация пустая )
![Screenshot_8](https://github.com/mstilkerich/rcmcarddav/assets/160089771/e62e6fa0-fcf7-444c-a9c9-99ce1003f106)
![Screenshot_9](https://github.com/mstilkerich/rcmcarddav/assets/160089771/472ea73e-3f9b-4dba-9abf-813c8a733cdc)
![Screenshot_10](https://github.com/mstilkerich/rcmcarddav/assets/160089771/11b298df-0ea6-41f7-8d01-8ae14fbc5932)
@mstilkerich Буду признателен вам за помощь !

**Comment by mstilkerich** [comment]
Hello,

  from your screenshots, I don't understand why you are getting syntax errors. Looks like the default file to me.

A valid `config.inc.php` for RCMCardDAV v4 with one example preset could look like this:

```php
<?php

$prefs['Davical'] = [
    'name'    =>  'Davical',
    'url'         =>  'http://davical.localdomain/',

    'username'     =>  '%u',
    'password'     =>  '%p',

    'fixed'        =>  [ 'username', 'password' ],
];
```

**Comment by sys-team-59** [comment]
Выходит одна и таже ошибка при добавлении адресной книги 
error adding address book from preset web could not determine the address book home
Название адресной книги нудно прописывать /var/www/roundcube/plugins/carddav/config.inc.php или не нужно ?
![Screenshot_11](https://github.com/mstilkerich/rcmcarddav/assets/160089771/d6704f70-2303-42ed-8e97-47a2fc701842)
@mstilkerich

**Comment by mstilkerich** [comment]
It means the location of the addressbooks cannot be found. Might be that your discovery DNS records are not properly set up, well-known URI redirect is missing, or just authentication is not working. Without more information I cannot help. HTTP debug log would be helpful.

**Comment by sys-team-59** [comment]
Доброе утро! Отправляю Log ошибки carddav_http.log
![Screenshot_1](https://github.co@mstilkerich /mstilkerich/rcmcarddav/assets/160089771/651011ee-cd98-4aec-b71b-f7d3653fa007)

@mstilkerich

**Comment by mstilkerich** [comment]
Well I guess you see the error message yourself. The hostname cannot be resolved, and in the second log entry the URL is malformed. Since you have redacted the relevant content I cannot tell you more than that.
