### ISSUE TITLE
Global dysfunction

### ISSUE THREAD

**Issue by grosjo** [mstilkerich/rcmcarddav#469]
Recent updates on dev (rouncube and/or cardav) make it globally unusable

These is an example of the errors I get

[18-Apr-2024 23:48:57 +0000]: <256f5499> [5 ERR] Could not get contact 11579: Expected Multistatus HTTP request was not successful (429 Too Many Requests): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\TooManyRequests</s:exception>
  <s:message/>
  <o:hint xmlns:o="o:">too many requests</o:hint>
</d:error>

**Comment by grosjo** [comment]
or like this
[18-Apr-2024 23:44:08 +0000]: <1e2c7f85> [4 WRN] Couldn't parse vcard BEGIN:VCARD^M
VERSION:3.0^M
UID:sabre-vobject-437dc7b3-cfeb-4145-a63a-717bc35a754e^M
PRODID:-//MStilkerich//RCMCardDAV v5.1.0//EN^M
REV:20240204T235049Z^M
N:(xxx);;;^M
ORG:9xxx0^M
FN:(xxx)^M
EMAIL;TYPE=work:(xxx)^M
TEL;TYPE=cell,voice:(xxx)^M
END:VCARD^M

**Comment by grosjo** [comment]
Other error reached 
[19-Apr-2024 05:09:13 +0000]: <7131d46f> [5 ERR] Error creating CardDAV account: Could not determine the addressbook home

**Comment by mstilkerich** [comment]
I have generalized the issue #468 regarding compatibility with roundcube 1.7. I'll look into it once the beta is released. Please don't open more issues regarding compatibility with unreleased versions of roundcube.

Just as a side note: The issues above ("too many requests" reported by server, discovery failing) seem not be related to roundcube/rcmcarddav compatibility.
