### ISSUE TITLE
RoundCube CardDAV sync issues with Synology

### ISSUE THREAD

**Issue by andrymango** [mstilkerich/rcmcarddav#474]
I use RoundCube and for a bunch of time I had Nextcloud installed on a personal server at home. RoundCube CardDAV plugin worked very fine with Nextcloud's cardDAV contacts: it found my contact list in seconds and went keeping it in sync as expected.

Just a month ago I bought a Synology NAS in place of the server. Synology's proprietary OS (DSM) has a contact app too, that can sync to any client via cardDAV. In fact. I have it synced with my phone (via DAVx5) and with Thunderbird (via CardBook): both found Synology Contacts immediately simply inserting its DAV URL. But I can't have it working at all with RoundCube CardDAV!

When I inserted the DAV URL for Nextcloud, it found the contact list immediately. But now, when I type the URL for Synology Contacts, it keeps searching for minutes and finally it stops but no contact list is found.

Further informations: RoundCube and CardDAV last releases, Synology DSM 7.2 (last update). It works fine with Nextcloud, not at all with Synology.

Is this a know problem? Does it exist a workaround to have RCMCardDAV working with Synology Contacts?

**Comment by mstilkerich** [comment]
Hi, there have been users with Synology before. If I remember correctly, Synology uses Radicale as server implementation. Could you enable http debug logging, try to add the account, and then provide the log? Then we can see where it goes wrong. Also the URL of an addressbook from one of the other clients might be helpful.

**Comment by andrymango** [comment]
Hi Michael and many thanks for the quick reply.
Could you please explain to me how to «enable http debug logging»? Then I will certainly provide the log.
Kind regards!

**Comment by mstilkerich** [comment]
Within your roundcube directory, you have to edit the file `plugins/carddav/config.inc.php`, and adjust the following lines there which set the loglevel to look like this:

```php
$prefs['_GLOBAL']['loglevel'] = \Psr\Log\LogLevel::DEBUG;
$prefs['_GLOBAL']['loglevel_http'] = \Psr\Log\LogLevel::DEBUG;
```

Make sure they are not commented out (in the default file, they are not).

Then try to add the addressbook via the user interface and wait until the process is completed.

Then you find (again within the roundcube installation directory) a log file `logs/carddav_http.log` and `logs/carddav.log`. Best provide both of them.

**Comment by mstilkerich** [comment]
Is this still relevant? Otherwise I‘ll close this issue.
