### ISSUE TITLE
Receive error message when adding a new CardDAV account

### ISSUE THREAD

**Issue by HookHM** [mstilkerich/rcmcarddav#476]
Hello everyone,

I have successfully installed the plugin, but I get an error message (see screenshot) when I try to add a new CardDAV account.
<img width="338" alt="Bildschirmfoto 2024-10-20 um 10 50 21" src="https://github.com/user-attachments/assets/ddd36254-4e51-4045-810c-dac9d6e97eff">

I understand the error that the address book directory has not been created, but where can I find out and then configure it?

I don't have much of a clue, have I done something wrong or do I need to configure something important?

Roundcube version 1.6.9 is installed.

Thank you already!

**Comment by mstilkerich** [comment]
The plugin tries to determine the "addressbook home" of the user, which you can think of as the parent directory ("collection") of the user's addressbooks. To figure out what exactly goes wrong, enable HTTP debug logging and look in the carddav_http.log after performing an attempt to add the addressbook in roundcube.

**Comment by HookHM** [comment]
This is the only entry in the log:
`[20-Oct-2024 09:17:39 +0000]: <4is49t3j> [5 ERR] Error creating CardDAV account: Could not determine the addressbook home `

**Comment by mstilkerich** [comment]
You need to look in `carddav_http.log`, not `carddav.log`. Also you need to set the loglevel to `DEBUG` first otherwise it will not be produced.

To do that, set
```php
$prefs['_GLOBAL']['loglevel_http'] = \Psr\Log\LogLevel::DEBUG;
```

in `plugins/carddav/config.inc.php`.

**Comment by HookHM** [comment]
This is how it is currently set up:
<img width="671" alt="Bildschirmfoto 2024-10-20 um 11 36 26" src="https://github.com/user-attachments/assets/534167a9-81b5-414d-baf2-46903d2d1803">


Could the reason be that Roundcube is installed via Plesk?

**Comment by HookHM** [comment]
@mstilkerich sorry, of course it wasn't on DEBUG

`[20-Oct-2024 09:41:35 +0000]: <grr0g3j1> [2 NFO] "PROPFIND /.well-known/carddav HTTP/1.1" 405
>>>>>>>>
PROPFIND /.well-known/carddav HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: XXXX.de
Depth: 0
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<
HTTP/1.1 405 Method Not Allowed
Server: nginx
Date: Sun, 20 Oct 2024 09:41:35 GMT
Content-Type: text/html
Content-Length: 818
Connection: keep-alive
Last-Modified: Sat, 19 Oct 2024 21:34:55 GMT
ETag: "332-624db30ce79be"
Accept-Ranges: bytes

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>405 Method Not Allowed</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">405</div>
    <h2>Method Not Allowed</h2>
    <p class="lead">The HTTP verb used to access this page is not allowed.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>


--------
NULL 
[20-Oct-2024 09:41:35 +0000]: <grr0g3j1> [2 NFO] "PROPFIND / HTTP/1.1" 405
>>>>>>>>
PROPFIND / HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: dnsvpn.de
Depth: 0
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<
HTTP/1.1 405 Method Not Allowed
Server: nginx
Date: Sun, 20 Oct 2024 09:41:35 GMT
Content-Type: text/html
Content-Length: 818
Connection: keep-alive
Last-Modified: Sat, 19 Oct 2024 21:34:55 GMT
ETag: "332-624db30ce79be"
Accept-Ranges: bytes

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>405 Method Not Allowed</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">405</div>
    <h2>Method Not Allowed</h2>
    <p class="lead">The HTTP verb used to access this page is not allowed.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>


--------
NULL 
[20-Oct-2024 09:41:35 +0000]: <grr0g3j1> [2 NFO] "PROPFIND /co HTTP/1.1" 405
>>>>>>>>
PROPFIND /co HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: XXXX.de
Depth: 0
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<
HTTP/1.1 405 Method Not Allowed
Server: nginx
Date: Sun, 20 Oct 2024 09:41:35 GMT
Content-Type: text/html
Content-Length: 818
Connection: keep-alive
Last-Modified: Sat, 19 Oct 2024 21:34:55 GMT
ETag: "332-624db30ce79be"
Accept-Ranges: bytes

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>405 Method Not Allowed</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">405</div>
    <h2>Method Not Allowed</h2>
    <p class="lead">The HTTP verb used to access this page is not allowed.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>


--------
NULL 
`

**Comment by HookHM** [comment]
@mstilkerich sorry, of course it wasn't on DEBUG

```shell
[20-Oct-2024 09:41:35 +0000]: <grr0g3j1> [2 NFO] "PROPFIND /.well-known/carddav HTTP/1.1" 405
>>>>>>>>
PROPFIND /.well-known/carddav HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: XXXX.de
Depth: 0
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<
HTTP/1.1 405 Method Not Allowed
Server: nginx
Date: Sun, 20 Oct 2024 09:41:35 GMT
Content-Type: text/html
Content-Length: 818
Connection: keep-alive
Last-Modified: Sat, 19 Oct 2024 21:34:55 GMT
ETag: "332-624db30ce79be"
Accept-Ranges: bytes

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>405 Method Not Allowed</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">405</div>
    <h2>Method Not Allowed</h2>
    <p class="lead">The HTTP verb used to access this page is not allowed.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>


--------
NULL 
[20-Oct-2024 09:41:35 +0000]: <grr0g3j1> [2 NFO] "PROPFIND / HTTP/1.1" 405
>>>>>>>>
PROPFIND / HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: XXXX.de
Depth: 0
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<
HTTP/1.1 405 Method Not Allowed
Server: nginx
Date: Sun, 20 Oct 2024 09:41:35 GMT
Content-Type: text/html
Content-Length: 818
Connection: keep-alive
Last-Modified: Sat, 19 Oct 2024 21:34:55 GMT
ETag: "332-624db30ce79be"
Accept-Ranges: bytes

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>405 Method Not Allowed</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">405</div>
    <h2>Method Not Allowed</h2>
    <p class="lead">The HTTP verb used to access this page is not allowed.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>


--------
NULL 
[20-Oct-2024 09:41:35 +0000]: <grr0g3j1> [2 NFO] "PROPFIND /co HTTP/1.1" 405
>>>>>>>>
PROPFIND /co HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: XXXX.de
Depth: 0
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<
HTTP/1.1 405 Method Not Allowed
Server: nginx
Date: Sun, 20 Oct 2024 09:41:35 GMT
Content-Type: text/html
Content-Length: 818
Connection: keep-alive
Last-Modified: Sat, 19 Oct 2024 21:34:55 GMT
ETag: "332-624db30ce79be"
Accept-Ranges: bytes

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>405 Method Not Allowed</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">405</div>
    <h2>Method Not Allowed</h2>
    <p class="lead">The HTTP verb used to access this page is not allowed.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>


--------
NULL 

```

**Comment by mstilkerich** [comment]
Could you give me a bit more information on your setup regarding the server, and which information you enter in the web interface. For the discovery to work, you need to either setup discovery via DNS SRV/TXT records or redirection in the Web-Server for the `/.well-known/carddav` URI to point to an URI where the CardDAV server will answer requests for current user principal and addressbook-home.

If you do not setup any of these, you could still give the URI in the user-interface yourself.

**Comment by mstilkerich** [comment]
See here for nextcloud, for example, regarding setup of discovery via well-known URI:
https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

And/Or DNS:
https://help.nextcloud.com/t/advanced-dns-configuration-srv-records-for-carddavs-caldavs/43939

**Comment by HookHM** [comment]
It is a Debian server and Roundcube is installed via Plesk.

I enter this in the interface:
<img width="741" alt="Bildschirmfoto 2024-10-20 um 11 56 02" src="https://github.com/user-attachments/assets/8511d677-ede6-47ec-a872-0b2c21d62c88">

**Comment by mstilkerich** [comment]
What server are you using? Have you set it up yourself? As I wrote, if you expect discovery to work by just given a domain name as discovery URL, it must be properly set up. Otherwise try with the full URL of an addressbook.

**Comment by HookHM** [comment]
I set up the server myself. The address book is also on Roundcube, so I use the Roundcube address book. Unfortunately, I don't know the URL for the Roundcube address book. I would like to be able to receive the contacts from Roundcube via CardDAV on my iPhone.

**Comment by mstilkerich** [comment]
Hmm do I understand correctly:
* You use the roundcube built-in addressbook to manage your contacts
* You want your phone to access the internal addressbook of roundcube

That is not possible using this plugin, as it would require a CardDAV service to be offered by Roundcube. What this plugin allows you to do is add addressbooks stored in a CardDAV server to Roundcube and use them instead or in addition to the built-in one.

What about simply using iCloud for you contacts? You can add the iCloud addressbook to Roundcube using this plugin. You need to create an application-specific password instead of using your main apple password:
https://support.apple.com/en-us/102654

Then you can copy all the contacts from the roundcube addressbook to iCloud by using this plugin inside the roundcube contacts interface.

Then you have a shared addressbook between your phone and roundcube, which is hosted by Apple.

**Comment by HookHM** [comment]
Ah, okay. Then I misunderstood, it's exactly the other way around what this plugin does here and what I want. Thank you very much for your help.

**Comment by mstilkerich** [comment]
Ok! If you want to host the addressbook yourself, you would have to setup a CardDAV server yourself. Options are Baïkal, Radicale for a simple CardDAV service, or Nextcloud / Owncloud with all the additional stuff it brings.
