### ISSUE TITLE
Automatically remove deleted address books.

### ISSUE THREAD

**Issue by jhenninger** [mstilkerich/rcmcarddav#48]
I'm using this plugin with ownCloud and auto-discovery of address books which is working fine. Newly created address books in ownCloud are automatically added in Roundcube.

However, if an address book is deleted on ownCloud, it is not removed completely from  Roundcube. Instead it will show up as an empty group (Roundcube calls address books "groups"). It will also still appear in the CardDAV settings in Roundcube with no way for the user to delete it. 

My auto discovery preset:

``` php
$prefs['ownCloud'] = array(
    'name'         =>  'ownCloud',
    'username'     =>  '%l',
    'password'     =>  '%p',
    'url'          =>  'https://cloud.example.com/remote.php/carddav/addressbooks/%l/',
    'carddav_name_only' => true,
    'active'       =>  true,
    'readonly'     =>  false,
    'refresh_time' => '00:05:00',
    'preemptive_auth' => true,

    'fixed'        =>  array( 'username', 'password', 'refresh_time', 'preemptive_auth' ),
    'hide'         =>  false,
);
```

**Comment by t3chguy** [comment]
+1
Any news on this?
Very infrequently do I delete an addressbook, but it has happened, it stays in your plugins db but it removes all the contacts from within it. [Using Owncloud 8.0.2]

**Comment by blind-coder** [comment]
There's a "Delete addressbook" button in the settings.
Otherwise, no real news at the moment, sorry. Trying to get some other stuff production ready at the moment.

**Comment by t3chguy** [comment]
I've got it hidden, but thanks anyway.
